### ISSUE TITLE
Error with MR Robot TV SHOW

### ISSUE THREAD

**Issue by Samb00** [OstlerDev/PopcornTV#133]
Every time i try to play the TV SHOW MR Robot i got the same Error 

Error: ENOENT, no such file or directory 'tmp.jpg'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at Function.images.loadFromFile (/Users/samuelmakeen/Desktop/PopcornTV/node_modules/images/index.js:159:37)
    at images (/Users/samuelmakeen/Desktop/PopcornTV/node_modules/images/index.js:127:24)
    at WriteStream.<anonymous> (/Users/samuelmakeen/Desktop/PopcornTV/fanartGenerator.js:60:21)
    at WriteStream.emit (events.js:129:20)
    at finishMaybe (_stream_writable.js:484:14)
    at afterWrite (_stream_writable.js:362:3)
    at onwrite (_stream_writable.js:352:7)

**Comment by OstlerDev** [comment]
Could you please post your full debug log? Follow this guide: https://github.com/OstlerDev/PopcornTV/wiki/How-to-report-an-issue

**Comment by OstlerDev** [comment]
Also, what episode/season are you trying to watch?

**Comment by Samb00** [comment]
i get the same Error with all episodes 
the full log is here 
2015-07-27T04:44:20.098Z - notice: Starting PopcornTV
2015-07-27T04:44:20.102Z - DNS: DnsProxy binding on 192.168.0.2:53
2015-07-27T04:44:20.449Z - Web: listening on 192.168.0.2:80
2015-07-27T04:44:20.451Z - Web: SSL Web: listening on 192.168.0.2:443
2015-07-27T04:44:21.249Z - DNS: init.itunes.apple.com
2015-07-27T04:44:22.964Z - DNS: bookkeeper.itunes.apple.com
2015-07-27T04:44:22.968Z - DNS: xp.apple.com
2015-07-27T04:44:23.102Z - DNS: itunes.apple.com
2015-07-27T04:44:26.152Z - DNS: upp.itunes.apple.com
2015-07-27T04:44:27.843Z - DNS: appleglobal.102.112.2o7.net
2015-07-27T04:44:28.591Z - DNS: pd-nk.itunes.apple.com
2015-07-27T04:44:29.723Z - DNS: a3.mzstatic.com
2015-07-27T04:44:30.369Z - DNS: a4.mzstatic.com
2015-07-27T04:44:30.373Z - DNS: a2.mzstatic.com
2015-07-27T04:44:30.391Z - DNS: a5.mzstatic.com
2015-07-27T04:44:30.396Z - DNS: a1.mzstatic.com
2015-07-27T04:44:35.386Z - Web: SSL: js/application.js
2015-07-27T04:44:35.539Z - Web: templates/navbar.xml
2015-07-27T04:44:35.776Z - Web: /js/utils.js
2015-07-27T04:44:35.815Z - Web: /js/navbarHandler.js
2015-07-27T04:44:35.892Z - Web: templates/index.xml
2015-07-27T04:44:36.020Z - Web: /js/utils.js
2015-07-27T04:44:36.704Z - Web: /Parade.xml
2015-07-27T04:44:39.592Z - Web: /Parade.xml
2015-07-27T04:44:39.614Z - Web: templates/TVNav.xml
2015-07-27T04:44:39.746Z - Web: /js/utils.js
2015-07-27T04:44:39.780Z - Web: /js/navbarHandler.js
2015-07-27T04:44:39.940Z - Web: /TVGrid.xml
2015-07-27T04:44:40.878Z - Web: /js/utils.js
2015-07-27T04:44:43.171Z - Web: /TVGrid.xml
2015-07-27T04:44:44.241Z - Web: /js/utils.js
2015-07-27T04:45:05.931Z - Web: /seasons.xml
2015-07-27T04:45:06.841Z - Web: /cache/tt4158110-1080.jpg
2015-07-27T04:45:09.279Z - Web: /episodes.xml
2015-07-27T04:45:10.319Z - Web: /js/utils.js
2015-07-27T04:45:14.477Z - Web: /TVPrePlay.xml

**Comment by OstlerDev** [comment]
Can you please post the full log in debug mode? https://github.com/OstlerDev/PopcornTV/wiki/How-to-report-an-issue

**Comment by Samb00** [comment]
aTVSettings.json

{
    "C0KPG0XNFF54": {
        "quality": "720p",
        "fanart": "On",
        "subtitle": "Off",
        "keep": "Off",
        "favorites": [
            {
                "type": "movie",
                "id": "4279"
            },
            {
                "type": "movie",
                "id": "3683"
            },
            {
                "type": "movie",
                "id": "3803"
            }
        ]
    }
}

**Comment by OstlerDev** [comment]
I need you to post the full log by running PopcornTV in Debug mode @Samb00 , just copying the default output to here is not enough.

**Comment by Samb00** [comment]
i'm sorry but i don't know how to do that, the site not allow me to upload the files

**Comment by OstlerDev** [comment]
@Samb00 it clearly describes step by step on how to get it in debug mode, you also need to open the file and copy the contents. https://github.com/OstlerDev/PopcornTV/wiki/How-to-report-an-issue

**Comment by Samb00** [comment]
every time i try to upload the file i get the same error do you have email i send you the file on ? 
[screen shot 2015-07-26 at 10 23 52 pm](https://cloud.githubusercontent.com/assets/13514804/8899119/01dcb8be-33e5-11e5-9de6-2f6a89431497.png)

**Comment by OstlerDev** [comment]
As it says in step 6, please upload the log to either a [Github Gist](http://gist.github.com) or onto [Pastebin](http://pastebin.com). Those are two websites that you can post it to. Then post back a link.

**Comment by Samb00** [comment]
here you go 
PopcornTV Log
http://pastebin.com/RGATJCRc
aTVSettings
{
    "C0KPG0XNFF54": {
        "quality": "720p",
        "fanart": "On",
        "subtitle": "Off",
        "keep": "Off",
        "favorites": [
            {
                "type": "movie",
                "id": "4279"
            },
            {
                "type": "movie",
                "id": "3683"
            },
            {
                "type": "movie",
                "id": "3803"
            }
        ]
    }
}

**Comment by masonjames** [comment]
@Samb00 it looks like there are no seeders for the TV Show Mr Robot. PopcornTV uses the same sources as PopcornTime, I believe, and only has a limited amount of torrents to look through.  We've discussed using an alternate over on #36.

I'll let someone else confirm, but it just looks like a lack of available torrents in this case.

**Comment by Samb00** [comment]
@masonjames i tried it on Popcorn time it's working fine

**Comment by OstlerDev** [comment]
@masonjames All Magnet Links show seeders and peers as 0, so this is not the issue.

The issue rather seems to be that the thumbnail is null. Pushing up a commit now that should fix it @Samb00

**Comment by Samb00** [comment]
Thank you so much the latest update fixed the both bugs #133 #137 
Great Work Also it's a great Idea to add the buffering Status 

keep the great work up.
