### ISSUE TITLE
Error with Subtitules 

### ISSUE THREAD

**Issue by NicoSegoviaC** [OstlerDev/PopcornTV#138]
I'm just running PopCorn Tv in my apple tv, and everything seems to works well, but wen i set the spanish subtitles the program crush down. Without subtitules, the streaming works.
This is the error:

Streamer: Streamer: Starting Stream... Please wait for stream to be ready.
Web: /Movies/MoviePlay.xml
Streamer: Ready to Stream, binding to http://192.168.0.6:9999
Web: /subtitle.json
/Users/nicosegovia/Desktop/PopcornTV/SubtitleAPI.js:241
r: parseInt(color[1], 16)/255,
^
TypeError: Cannot read property '1' of null
at /Users/nicosegovia/Desktop/PopcornTV/SubtitleAPI.js:241:42
at Array.forEach (native)
at /Users/nicosegovia/Desktop/PopcornTV/SubtitleAPI.js:194:18
at /Users/nicosegovia/Desktop/PopcornTV/SubtitleAPI.js:133:25
at /Users/nicosegovia/Desktop/PopcornTV/node_modules/xmlrpc/lib/client.js:130:9
at callback (/Users/nicosegovia/Desktop/PopcornTV/node_modules/xmlrpc/lib/deserializer.js:42:7)
at Deserializer.onDone (/Users/nicosegovia/Desktop/PopcornTV/node_modules/xmlrpc/lib/deserializer.js:92:12)
at SAXStream.emit (events.js:104:17)
at Object.SAXStream._parser.onend (/Users/nicosegovia/Desktop/PopcornTV/node_modules/xmlrpc/node_modules/sax/lib/sax.js:184:8)
at emit (/Users/nicosegovia/Desktop/PopcornTV/node_modules/xmlrpc/node_modules/sax/lib/sax.js:615:33)

Any idea?

Thanks in advance

**Comment by OstlerDev** [comment]
@NicoSegoviaC what Movie/TV Show (as well as season and episode number). Here is how to accurately post an issue: https://github.com/OstlerDev/PopcornTV/wiki/How-to-report-an-issue

**Comment by OstlerDev** [comment]
Also, please update to the latest version as this might have been fixed already.

**Comment by pitercio** [comment]
I had the same problem, and it solved it by using "sudo npm install".

**Comment by OstlerDev** [comment]
Thanks for letting us know @pitercio !
