### ISSUE TITLE
First load of "popular" stuck on "accessing trailers"

### ISSUE THREAD

**Issue by krugster** [OstlerDev/PopcornTV#192]
When I first select either Movies or TV Shows, it goes to the "popular" search mode and spins constantly on "Accessing trailers".  If I switch over to "recently updated", it loads without any spinning circle and then when I switch back to "popular" it displays the list of shows.

Now of course I'm having a bit of a hard time reproducing, but it seems to be stuck on loading /js/utils.js:
2015-08-17T02:05:04.074Z - Web: /js/navbarHandler.js
2015-08-17T02:05:04.194Z - Web: /MoviesGrid.xml
2015-08-17T02:05:04.679Z - Web: /js/utils.js
2015-08-17T02:05:17.651Z - Web: /MoviesGrid.xml

You can see that there is a ~13s delay between the second to last log line and the last...

I've tried a couple times to reproduce this but can't seem to, perhaps it's getting cached somewhere in the ATV or on the popcorntv side?

**Comment by krugster** [comment]
I think I caught it, there are a couple "uncaught exceptions" in the logs:
2015-08-17T02:13:39.262Z - notice: Starting PopcornTV
2015-08-17T02:13:39.277Z - DNS: DnsProxy binding on 192.168.1.200:53
2015-08-17T02:13:40.099Z - Web: listening on 192.168.1.200:80
2015-08-17T02:13:40.104Z - Web: SSL Web: listening on 192.168.1.200:443
2015-08-17T02:13:40.139Z - notice: Starting Commit 
2015-08-17T02:14:05.116Z - DNS: setup.icloud.com
2015-08-17T02:14:05.116Z - DNS: www.apple.com
2015-08-17T02:14:05.586Z - DNS: local
2015-08-17T02:14:07.421Z - DNS: gs-loc.apple.com
2015-08-17T02:14:08.091Z - DNS: sr.symcd.com
2015-08-17T02:14:09.041Z - DNS: cl2.apple.com
2015-08-17T02:14:09.051Z - DNS: cl5.apple.com
2015-08-17T02:14:09.741Z - DNS: init.ess.apple.com
2015-08-17T02:14:10.906Z - DNS: init.itunes.apple.com
2015-08-17T02:14:11.651Z - DNS: itunes.apple.com
2015-08-17T02:14:11.656Z - DNS: xp.apple.com
2015-08-17T02:14:12.182Z - DNS: bookkeeper.itunes.apple.com
2015-08-17T02:14:12.512Z - DNS: time-ios.apple.com
2015-08-17T02:14:15.994Z - DNS: p19-buy.itunes.apple.com
2015-08-17T02:14:22.535Z - DNS: play.itunes.apple.com
2015-08-17T02:14:22.820Z - DNS: sb.symcd.com
2015-08-17T02:14:23.480Z - DNS: radio.itunes.apple.com
2015-08-17T02:14:24.570Z - DNS: se.itunes.apple.com
2015-08-17T02:14:28.251Z - DNS: a1.mzstatic.com
2015-08-17T02:14:28.781Z - DNS: partiality.itunes.apple.com
2015-08-17T02:14:28.811Z - DNS: a3.mzstatic.com
2015-08-17T02:14:28.826Z - DNS: init-p01st.push.apple.com
2015-08-17T02:14:28.831Z - DNS: a5.mzstatic.com
2015-08-17T02:14:28.846Z - DNS: a4.mzstatic.com
2015-08-17T02:14:28.856Z - DNS: a2.mzstatic.com
2015-08-17T02:14:30.471Z - DNS: iadsdk.apple.com
2015-08-17T02:14:30.886Z - DNS: 18-courier.push.apple.com
2015-08-17T02:14:37.036Z - DNS: e3191.dscc.akamaiedge.net
2015-08-17T02:14:37.616Z - DNS: pd-nk.itunes.apple.com
2015-08-17T02:14:39.652Z - DNS: configuration.apple.com
2015-08-17T02:14:45.163Z - DNS: p01-keyvalueservice.icloud.com
2015-08-17T02:14:45.293Z - DNS: keyvalueservice.icloud.com
2015-08-17T02:14:56.379Z - DNS: e7542.e9.akamaiedge.net
2015-08-17T02:14:56.989Z - DNS: is3.mzstatic.com
2015-08-17T02:14:56.994Z - DNS: is2.mzstatic.com
2015-08-17T02:14:56.999Z - DNS: is5.mzstatic.com
2015-08-17T02:14:58.214Z - Web: SSL: js/application.js
2015-08-17T02:14:58.329Z - Web: templates/navbar.xml
2015-08-17T02:14:58.519Z - Web: /js/utils.js
2015-08-17T02:14:58.544Z - Web: /js/navbarHandler.js
2015-08-17T02:14:58.644Z - Web: templates/index.xml
2015-08-17T02:14:58.719Z - Web: /js/utils.js
2015-08-17T02:14:59.354Z - Web: /Parade.xml
2015-08-17T02:15:00.629Z - DNS: s.ynet.io
2015-08-17T02:15:00.694Z - Web: templates/MovieNav.xml
2015-08-17T02:15:00.939Z - Web: /js/utils.js
2015-08-17T02:15:01.079Z - Web: /js/navbarHandler.js
2015-08-17T02:15:01.169Z - Web: /MoviesGrid.xml
2015-08-17T02:15:02.659Z - Web: /js/utils.js
2015-08-17T02:15:03.610Z - DNS: init-p01md.apple.com
2015-08-17T02:15:46.135Z - Web: /settings.xml
2015-08-17T02:15:46.250Z - Web: /js/utils.js
2015-08-17T02:15:46.265Z - Web: /js/settings.js
2015-08-17T02:15:46.460Z - Web: /thumbnails/Logo.png
2015-08-17T02:15:48.350Z - error: uncaughtException: first argument must be a string or Buffer 
{ date: 'Sun Aug 16 2015 19:15:48 GMT-0700 (Pacific Daylight Time)',
  process: 
   { pid: 3780,
     uid: null,
     gid: null,
     cwd: 'C:\\Windows\\system32',
     execPath: 'C:\\Program Files (x86)\\nodejs\\node.exe',
     version: 'v0.12.7',
     argv: 
      [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
        'C:\\Users\\pkrug\\PopcornTV\\atv.js' ],
     memoryUsage: { rss: 51609600, heapTotal: 35318016, heapUsed: 22578860 } },
  os: { loadavg: [ 0, 0, 0 ], uptime: 402389.0562369 },
  trace: 
   [ { column: 11,
       file: '_http_outgoing.js',
       function: 'ServerResponse.OutgoingMessage.write',
       line: 433,
       method: 'OutgoingMessage.write',
       native: false },
     { column: 14,
       file: 'C:\\Users\\pkrug\\PopcornTV\\webserver.js',
       function: null,
       line: 477,
       method: null,
       native: false },
     { column: 12,
       file: 'C:\\Users\\pkrug\\PopcornTV\\node_modules\\xml-writer\\lib\\xml-writer.js',
       function: 'strval',
       line: 14,
       method: null,
       native: false },
     { column: 19,
       file: 'C:\\Users\\pkrug\\PopcornTV\\node_modules\\xml-writer\\lib\\xml-writer.js',
       function: 'Object.XMLWriter.text',
       line: 253,
       method: 'XMLWriter.text',
       native: false },
     { column: 40,
       file: 'C:\\Users\\pkrug\\PopcornTV\\node_modules\\xml-writer\\lib\\xml-writer.js',
       function: 'Object.XMLWriter.writeElement',
       line: 114,
       method: 'XMLWriter.writeElement',
       native: false },
     { column: 34,
       file: 'C:\\Users\\pkrug\\PopcornTV\\XMLGenerator.js',
       function: 'Object.generateSettingsXML',
       line: 362,
       method: 'generateSettingsXML',
       native: false },
     { column: 8,
       file: 'C:\\Users\\pkrug\\PopcornTV\\webserver.js',
       function: '',
       line: 475,
       method: null,
       native: false },
     { column: 17,
       file: 'events.js',
       function: 'Server.emit',
       line: 110,
       method: 'emit',
       native: false },
     { column: 12,
       file: '_http_server.js',
       function: 'HTTPParser.parserOnIncoming [as onIncoming]',
       line: 491,
       method: 'parserOnIncoming [as onIncoming]',
       native: false },
     { column: 23,
       file: '_http_common.js',
       function: 'HTTPParser.parserOnHeadersComplete',
       line: 111,
       method: 'parserOnHeadersComplete',
       native: false } ],
  stack: 
   [ 'TypeError: first argument must be a string or Buffer',
     '    at ServerResponse.OutgoingMessage.write (_http_outgoing.js:433:11)',
     '    at C:\\Users\\pkrug\\PopcornTV\\webserver.js:477:14',
     '    at strval (C:\\Users\\pkrug\\PopcornTV\\node_modules\\xml-writer\\lib\\xml-writer.js:14:12)',
     '    at Object.XMLWriter.text (C:\\Users\\pkrug\\PopcornTV\\node_modules\\xml-writer\\lib\\xml-writer.js:253:19)',
     '    at Object.XMLWriter.writeElement (C:\\Users\\pkrug\\PopcornTV\\node_modules\\xml-writer\\lib\\xml-writer.js:114:40)',
     '    at Object.generateSettingsXML (C:\\Users\\pkrug\\PopcornTV\\XMLGenerator.js:362:34)',
     '    at Server.<anonymous> (C:\\Users\\pkrug\\PopcornTV\\webserver.js:475:8)',
     '    at Server.emit (events.js:110:17)',
     '    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:491:12)',
     '    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)' ] }
2015-08-17T02:16:06.617Z - Web: SSL: js/application.js
2015-08-17T02:16:06.722Z - Web: templates/navbar.xml
2015-08-17T02:16:06.812Z - Web: /js/utils.js
2015-08-17T02:16:06.832Z - Web: /js/navbarHandler.js
2015-08-17T02:16:06.927Z - Web: templates/index.xml
2015-08-17T02:16:07.002Z - Web: /js/utils.js
2015-08-17T02:16:07.567Z - Web: /Parade.xml
2015-08-17T02:16:08.137Z - Web: templates/Search/search.xml
2015-08-17T02:16:08.978Z - Web: templates/index.xml
2015-08-17T02:16:09.013Z - Web: /js/utils.js
2015-08-17T02:16:09.558Z - Web: /Parade.xml
2015-08-17T02:16:10.563Z - Web: templates/TVNav.xml
2015-08-17T02:16:10.718Z - Web: /Parade.xml
2015-08-17T02:16:10.738Z - Web: /js/utils.js
2015-08-17T02:16:10.758Z - Web: /js/navbarHandler.js
2015-08-17T02:16:10.858Z - Web: /TVGrid.xml
2015-08-17T02:16:11.403Z - Web: /js/utils.js
2015-08-17T02:16:49.163Z - error: uncaughtException: first argument must be a string or Buffer 
{ date: 'Sun Aug 16 2015 19:16:49 GMT-0700 (Pacific Daylight Time)',
  process: 
   { pid: 3780,
     uid: null,
     gid: null,
     cwd: 'C:\\Windows\\system32',
     execPath: 'C:\\Program Files (x86)\\nodejs\\node.exe',
     version: 'v0.12.7',
     argv: 
      [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
        'C:\\Users\\pkrug\\PopcornTV\\atv.js' ],
     memoryUsage: { rss: 51662848, heapTotal: 37337216, heapUsed: 18892576 } },
  os: { loadavg: [ 0, 0, 0 ], uptime: 402449.8693225 },
  trace: 
   [ { column: 11,
       file: '_http_outgoing.js',
       function: 'ServerResponse.OutgoingMessage.write',
       line: 433,
       method: 'OutgoingMessage.write',
       native: false },
     { column: 14,
       file: 'C:\\Users\\pkrug\\PopcornTV\\webserver.js',
       function: null,
       line: 477,
       method: null,
       native: false },
     { column: 12,
       file: 'C:\\Users\\pkrug\\PopcornTV\\node_modules\\xml-writer\\lib\\xml-writer.js',
       function: 'strval',
       line: 14,
       method: null,
       native: false },
     { column: 19,
       file: 'C:\\Users\\pkrug\\PopcornTV\\node_modules\\xml-writer\\lib\\xml-writer.js',
       function: 'Object.XMLWriter.text',
       line: 253,
       method: 'XMLWriter.text',
       native: false },
     { column: 40,
       file: 'C:\\Users\\pkrug\\PopcornTV\\node_modules\\xml-writer\\lib\\xml-writer.js',
       function: 'Object.XMLWriter.writeElement',
       line: 114,
       method: 'XMLWriter.writeElement',
       native: false },
     { column: 34,
       file: 'C:\\Users\\pkrug\\PopcornTV\\XMLGenerator.js',
       function: 'Object.generateSettingsXML',
       line: 362,
       method: 'generateSettingsXML',
       native: false },
     { column: 8,
       file: 'C:\\Users\\pkrug\\PopcornTV\\webserver.js',
       function: '',
       line: 475,
       method: null,
       native: false },
     { column: 17,
       file: 'events.js',
       function: 'Server.emit',
       line: 110,
       method: 'emit',
       native: false },
     { column: 12,
       file: '_http_server.js',
       function: 'HTTPParser.parserOnIncoming [as onIncoming]',
       line: 491,
       method: 'parserOnIncoming [as onIncoming]',
       native: false },
     { column: 23,
       file: '_http_common.js',
       function: 'HTTPParser.parserOnHeadersComplete',
       line: 111,
       method: 'parserOnHeadersComplete',
       native: false } ],
  stack: 
   [ 'TypeError: first argument must be a string or Buffer',
     '    at ServerResponse.OutgoingMessage.write (_http_outgoing.js:433:11)',
     '    at C:\\Users\\pkrug\\PopcornTV\\webserver.js:477:14',
     '    at strval (C:\\Users\\pkrug\\PopcornTV\\node_modules\\xml-writer\\lib\\xml-writer.js:14:12)',
     '    at Object.XMLWriter.text (C:\\Users\\pkrug\\PopcornTV\\node_modules\\xml-writer\\lib\\xml-writer.js:253:19)',
     '    at Object.XMLWriter.writeElement (C:\\Users\\pkrug\\PopcornTV\\node_modules\\xml-writer\\lib\\xml-writer.js:114:40)',
     '    at Object.generateSettingsXML (C:\\Users\\pkrug\\PopcornTV\\XMLGenerator.js:362:34)',
     '    at Server.<anonymous> (C:\\Users\\pkrug\\PopcornTV\\webserver.js:475:8)',
     '    at Server.emit (events.js:110:17)',
     '    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:491:12)',
     '    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)' ] }
2015-08-17T02:17:49.306Z - error: uncaughtException: first argument must be a string or Buffer 
{ date: 'Sun Aug 16 2015 19:17:49 GMT-0700 (Pacific Daylight Time)',
  process: 
   { pid: 3780,
     uid: null,
     gid: null,
     cwd: 'C:\\Windows\\system32',
     execPath: 'C:\\Program Files (x86)\\nodejs\\node.exe',
     version: 'v0.12.7',
     argv: 
      [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
        'C:\\Users\\pkrug\\PopcornTV\\atv.js' ],
     memoryUsage: { rss: 52064256, heapTotal: 37337216, heapUsed: 19551424 } },
  os: { loadavg: [ 0, 0, 0 ], uptime: 402510.0174083 },
  trace: 
   [ { column: 11,
       file: '_http_outgoing.js',
       function: 'ServerResponse.OutgoingMessage.write',
       line: 433,
       method: 'OutgoingMessage.write',
       native: false },
     { column: 14,
       file: 'C:\\Users\\pkrug\\PopcornTV\\webserver.js',
       function: null,
       line: 477,
       method: null,
       native: false },
     { column: 12,
       file: 'C:\\Users\\pkrug\\PopcornTV\\node_modules\\xml-writer\\lib\\xml-writer.js',
       function: 'strval',
       line: 14,
       method: null,
       native: false },
     { column: 19,
       file: 'C:\\Users\\pkrug\\PopcornTV\\node_modules\\xml-writer\\lib\\xml-writer.js',
       function: 'Object.XMLWriter.text',
       line: 253,
       method: 'XMLWriter.text',
       native: false },
     { column: 40,
       file: 'C:\\Users\\pkrug\\PopcornTV\\node_modules\\xml-writer\\lib\\xml-writer.js',
       function: 'Object.XMLWriter.writeElement',
       line: 114,
       method: 'XMLWriter.writeElement',
       native: false },
     { column: 34,
       file: 'C:\\Users\\pkrug\\PopcornTV\\XMLGenerator.js',
       function: 'Object.generateSettingsXML',
       line: 362,
       method: 'generateSettingsXML',
       native: false },
     { column: 8,
       file: 'C:\\Users\\pkrug\\PopcornTV\\webserver.js',
       function: '',
       line: 475,
       method: null,
       native: false },
     { column: 17,
       file: 'events.js',
       function: 'Server.emit',
       line: 110,
       method: 'emit',
       native: false },
     { column: 12,
       file: '_http_server.js',
       function: 'HTTPParser.parserOnIncoming [as onIncoming]',
       line: 491,
       method: 'parserOnIncoming [as onIncoming]',
       native: false },
     { column: 23,
       file: '_http_common.js',
       function: 'HTTPParser.parserOnHeadersComplete',
       line: 111,
       method: 'parserOnHeadersComplete',
       native: false } ],
  stack: 
   [ 'TypeError: first argument must be a string or Buffer',
     '    at ServerResponse.OutgoingMessage.write (_http_outgoing.js:433:11)',
     '    at C:\\Users\\pkrug\\PopcornTV\\webserver.js:477:14',
     '    at strval (C:\\Users\\pkrug\\PopcornTV\\node_modules\\xml-writer\\lib\\xml-writer.js:14:12)',
     '    at Object.XMLWriter.text (C:\\Users\\pkrug\\PopcornTV\\node_modules\\xml-writer\\lib\\xml-writer.js:253:19)',
     '    at Object.XMLWriter.writeElement (C:\\Users\\pkrug\\PopcornTV\\node_modules\\xml-writer\\lib\\xml-writer.js:114:40)',
     '    at Object.generateSettingsXML (C:\\Users\\pkrug\\PopcornTV\\XMLGenerator.js:362:34)',
     '    at Server.<anonymous> (C:\\Users\\pkrug\\PopcornTV\\webserver.js:475:8)',
     '    at Server.emit (events.js:110:17)',
     '    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:491:12)',
     '    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)' ] }
2015-08-17T02:18:16.785Z - Web: /TVGrid.xml
2015-08-17T02:18:17.900Z - Web: /js/utils.js
2015-08-17T02:18:18.130Z - DNS: walter.trakt.us
2015-08-17T02:18:20.105Z - Web: /TVGrid.xml
2015-08-17T02:18:21.170Z - Web: /js/utils.js

At the end, I switched to the "Recently Updated" tab and then back again to "Popular" and it loaded properly.

Although I'm worried that might not be it since I didn't see those same message in the logs before, but this is definitely capturing all the logs from startup through to where I was able to see the TV listings at the end.

**Comment by OstlerDev** [comment]
This happens because there are ongoing requests that the Apple TV is making. Since the request for the parade has not been fulfilled it attempts to serve it to the "Popular" page.

This is a bug that I want to get fixed.
