### ISSUE TITLE
Subtitles not working - v0.1.13 only, OSX

### ISSUE THREAD

**Issue by Mauricevb** [OstlerDev/PopcornTV#194]
When I try to watch a movie after I selected the subtitle language, I get the following error in my Terminal:

```
Web: /subtitle.json
error: uncaughtException: Object #<Object> has no method 'gunzipSync' 
{ date: 'Tue Aug 18 2015 15:19:13 GMT+0200 (CEST)',
  process: 
   { pid: 61515,
     uid: 0,
     gid: 0,
     cwd: '/Users/Maurice/PopcornTV',
     execPath: '/usr/local/bin/node',
     version: 'v0.10.36',
     argv: 
      [ 'node',
        '/Users/Maurice/PopcornTV/atv.js' ],
     memoryUsage: 
      { rss: 133586944,
        heapTotal: 70571008,
        heapUsed: 46335512 } },
  os: 
   { loadavg: 
      [ 1.2490234375,
        1.35791015625,
        1.458984375 ],
     uptime: 2353363 },
  trace: 
   [ { column: 45,
       file: '/Users/Maurice/PopcornTV/SubtitleAPI.js',
       function: null,
       line: 151,
       method: null,
       native: false },
     { column: 9,
       file: '/Users/Maurice/PopcornTV/node_modules/xmlrpc/lib/client.js',
       function: null,
       line: 130,
       method: null,
       native: false },
     { column: 7,
       file: '/Users/Maurice/PopcornTV/node_modules/xmlrpc/lib/deserializer.js',
       function: 'callback',
       line: 42,
       method: null,
       native: false },
     { column: 12,
       file: '/Users/Maurice/PopcornTV/node_modules/xmlrpc/lib/deserializer.js',
       function: 'Deserializer.onDone',
       line: 92,
       method: 'onDone',
       native: false },
     { column: 17,
       file: 'events.js',
       function: 'SAXStream.emit',
       line: 92,
       method: 'emit',
       native: false },
     { column: 8,
       file: '/Users/Maurice/PopcornTV/node_modules/xmlrpc/node_modules/sax/lib/sax.js',
       function: 'Object.SAXStream._parser.onend',
       line: 184,
       method: 'SAXStream._parser.onend',
       native: false },
     { column: 33,
       file: '/Users/Maurice/PopcornTV/node_modules/xmlrpc/node_modules/sax/lib/sax.js',
       function: 'emit',
       line: 615,
       method: null,
       native: false },
     { column: 3,
       file: '/Users/Maurice/PopcornTV/node_modules/xmlrpc/node_modules/sax/lib/sax.js',
       function: 'end',
       line: 654,
       method: null,
       native: false },
     { column: 24,
       file: '/Users/Maurice/PopcornTV/node_modules/xmlrpc/node_modules/sax/lib/sax.js',
       function: 'Object.SAXParser.end',
       line: 149,
       method: 'SAXParser.end',
       native: false },
     { column: 16,
       file: '/Users/Maurice/PopcornTV/node_modules/xmlrpc/node_modules/sax/lib/sax.js',
       function: 'SAXStream.end',
       line: 234,
       method: 'end',
       native: false } ],
  stack: 
   [ 'TypeError: Object #<Object> has no method \'gunzipSync\'',
     '    at /Users/Maurice/PopcornTV/SubtitleAPI.js:151:45',
     '    at /Users/Maurice/PopcornTV/node_modules/xmlrpc/lib/client.js:130:9',
     '    at callback (/Users/Maurice/PopcornTV/node_modules/xmlrpc/lib/deserializer.js:42:7)',
     '    at Deserializer.onDone (/Users/Maurice/PopcornTV/node_modules/xmlrpc/lib/deserializer.js:92:12)',
     '    at SAXStream.emit (events.js:92:17)',
     '    at Object.SAXStream._parser.onend (/Users/Maurice/PopcornTV/node_modules/xmlrpc/node_modules/sax/lib/sax.js:184:8)',
     '    at emit (/Users/Maurice/PopcornTV/node_modules/xmlrpc/node_modules/sax/lib/sax.js:615:33)',
     '    at end (/Users/Maurice/PopcornTV/node_modules/xmlrpc/node_modules/sax/lib/sax.js:654:3)',
     '    at Object.SAXParser.end (/Users/Maurice/PopcornTV/node_modules/xmlrpc/node_modules/sax/lib/sax.js:149:24)',
     '    at SAXStream.end (/Users/Maurice/PopcornTV/node_modules/xmlrpc/node_modules/sax/lib/sax.js:234:16)' ] }
```

**Comment by fadrizul** [comment]
PR #197 will fix your problem

**Comment by OstlerDev** [comment]
I did not realize that they changed the module, I will add this to tests when I write them.

Thanks @fadrizul
