### ISSUE TITLE
issues with running on ubuntu vm

### ISSUE THREAD

**Issue by churnd** [OstlerDev/PopcornTV#199]
Been checking this out the past two days & loving it.  I have a VM server at home & trying to get it running in an Ubuntu VM, but getting some errors.  I do want to say that I have it running fine on my laptop running OS X using node from homebrew, so I know it works somewhere.  On the ubuntu VM, running the latest node & iojs from the nodesource repos:

```
root@popcorn:/opt/PopcornTV# node -v
v1.8.4
root@popcorn:/opt/PopcornTV# iojs -v
v1.8.4
```

I can browse the UI OK but I get some errors when trying to play a TV show or video:

```
root@popcorn:/opt/PopcornTV# git pull
Already up-to-date.
root@popcorn:/opt/PopcornTV# node atv.js 
notice: Starting PopcornTV
DNS: DnsProxy binding on 192.168.1.208:53
Web: listening on 192.168.1.208:80
Web: SSL Web: listening on 192.168.1.208:443
notice: Starting Commit ab5d6e8
Web: SSL: js/application.js
Web: templates/navbar.xml
Web: /js/utils.js
Web: /js/navbarHandler.js
Web: templates/index.xml
Web: /js/utils.js
Web: /Parade.xml
Web: /Parade.xml
Web: templates/TVNav.xml
Web: /js/utils.js
Web: /js/navbarHandler.js
Web: /TVGrid.xml
Web: /js/utils.js
Web: /TVGrid.xml
Web: /js/utils.js
Web: /TVGrid.xml
Web: /js/utils.js
Web: /TVGrid.xml
Web: /TVGrid.xml
Web: /js/utils.js
Web: templates/TVNav.xml
Web: /js/utils.js
Web: /js/navbarHandler.js
Web: /TVGrid.xml
Web: /js/utils.js
Web: /TVGrid.xml
Web: /js/utils.js
Web: /seasons.xml
error: uncaughtException: Can't load the addon. Issue to: https://github.com/PopcornTV/node-images/issues 
{ date: 'Fri Aug 21 2015 10:03:41 GMT-0400 (EDT)',
  process: 
   { pid: 3127,
     uid: 0,
     gid: 0,
     cwd: '/opt/PopcornTV',
     execPath: '/usr/bin/iojs',
     version: 'v1.8.4',
     argv: [ '/usr/bin/iojs', '/opt/PopcornTV/atv.js' ],
     memoryUsage: { rss: 80523264, heapTotal: 60304384, heapUsed: 33701264 } },
  os: 
   { loadavg: [ 0.00390625, 0.02978515625, 0.04541015625 ],
     uptime: 40063 },
  trace: 
   [ { column: 7,
       file: '/opt/PopcornTV/node_modules/ptv-images/binding.js',
       function: '',
       line: 61,
       method: null,
       native: false },
     { column: 26,
       file: 'module.js',
       function: 'Module._compile',
       line: 428,
       method: '_compile',
       native: false },
     { column: 10,
       file: 'module.js',
       function: 'Object.Module._extensions..js',
       line: 446,
       method: 'Module._extensions..js',
       native: false },
     { column: 32,
       file: 'module.js',
       function: 'Module.load',
       line: 353,
       method: 'load',
       native: false },
     { column: 12,
       file: 'module.js',
       function: 'Function.Module._load',
       line: 308,
       method: 'Module._load',
       native: false },
     { column: 17,
       file: 'module.js',
       function: 'Module.require',
       line: 363,
       method: 'require',
       native: false },
     { column: 17,
       file: 'module.js',
       function: 'require',
       line: 382,
       method: null,
       native: false },
     { column: 15,
       file: '/opt/PopcornTV/node_modules/ptv-images/index.js',
       function: '',
       line: 4,
       method: null,
       native: false },
     { column: 26,
       file: 'module.js',
       function: 'Module._compile',
       line: 428,
       method: '_compile',
       native: false },
     { column: 10,
       file: 'module.js',
       function: 'Object.Module._extensions..js',
       line: 446,
       method: 'Module._extensions..js',
       native: false } ],
  stack: 
   [ 'Error: Can\'t load the addon. Issue to: https://github.com/PopcornTV/node-images/issues',
     '    at Object.<anonymous> (/opt/PopcornTV/node_modules/ptv-images/binding.js:61:7)',
     '    at Module._compile (module.js:428:26)',
     '    at Object.Module._extensions..js (module.js:446:10)',
     '    at Module.load (module.js:353:32)',
     '    at Function.Module._load (module.js:308:12)',
     '    at Module.require (module.js:363:17)',
     '    at require (module.js:382:17)',
     '    at Object.<anonymous> (/opt/PopcornTV/node_modules/ptv-images/index.js:4:15)',
     '    at Module._compile (module.js:428:26)',
     '    at Object.Module._extensions..js (module.js:446:10)' ] }
error: Error: Can't load the addon. Issue to: https://github.com/PopcornTV/node-images/issues
    at Object.<anonymous> (/opt/PopcornTV/node_modules/ptv-images/binding.js:61:7)
    at Module._compile (module.js:428:26)
    at Object.Module._extensions..js (module.js:446:10)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (/opt/PopcornTV/node_modules/ptv-images/index.js:4:15)
    at Module._compile (module.js:428:26)
    at Object.Module._extensions..js (module.js:446:10)
```

I also get errors when I try to go into certain settings, like subtitles.  Just hoping I can get it going in a VM that's running 24/7 rather than on my laptop that's not.

**Comment by OstlerDev** [comment]
The issue is that you are running iojs. You need to be running nodejs.

However, if you wish to help with iojs, then you can compile the binding and I can add it to the repository: https://github.com/PopcornTV/node-images/wiki/How-to-build-a-binding

**Comment by OstlerDev** [comment]
Please note that installing iojs after node will overwrite the path to the original node and just point to iojs, that is why it is giving you the same version for both.

**Comment by churnd** [comment]
Ah ok, good to know about iojs.

I started with a fresh VM where all I did was run `apt-get install nodejs` after setting up the nodesource repos as recommended by nodejs.org:  https://nodesource.com/blog/nodejs-v012-iojs-and-the-nodesource-linux-repositories.  Similar to what I did above except i didn't install iojs (only reason I installed it before is because I saw `npm install` say something about it not being there).

The movie seems to play fine, but still trying to get into certain areas of the menu gives crashes.  For example, going to Settings, Subtitles:

```
Streamer: Ready to Stream, binding to http://192.168.1.209:6354
Web: /progress.json
Web: /subtitle.json
Web: /StopStream.xml
Web: /MoviesGrid.xml
Web: templates/Search/movieSearch.xml
Web: /MoviesGrid.xml
Web: /MoviesGrid.xml
Web: /js/utils.js
Web: /settings.xml
Web: /js/utils.js
Web: /js/settings.js
Web: /thumbnails/Logo.png
Web: 404: /thumbnails/Logo.png
error: uncaughtException: Bad Parameter 
{ date: 'Fri Aug 21 2015 15:53:22 GMT-0400 (EDT)',
  process: 
   { pid: 2732,
     uid: 0,
     gid: 0,
     cwd: '/opt/PopcornTV',
     execPath: '/usr/bin/nodejs',
     version: 'v0.12.7',
     argv: [ 'node', '/opt/PopcornTV/atv.js' ],
     memoryUsage: { rss: 193953792, heapTotal: 96792064, heapUsed: 40421168 } },
  os: 
   { loadavg: [ 0.03564453125, 0.0263671875, 0.0458984375 ],
     uptime: 8942 },
  trace: 
   [ { column: null,
       file: null,
       function: 'Error',
       line: null,
       method: null,
       native: true },
     { column: 14,
       file: '/opt/PopcornTV/node_modules/xml-writer/lib/xml-writer.js',
       function: 'strval',
       line: 19,
       method: null,
       native: false },
     { column: 19,
       file: '/opt/PopcornTV/node_modules/xml-writer/lib/xml-writer.js',
       function: 'Object.XMLWriter.text',
       line: 253,
       method: 'XMLWriter.text',
       native: false },
     { column: 40,
       file: '/opt/PopcornTV/node_modules/xml-writer/lib/xml-writer.js',
       function: 'Object.XMLWriter.writeElement',
       line: 114,
       method: 'XMLWriter.writeElement',
       native: false },
     { column: 34,
       file: '/opt/PopcornTV/XMLGenerator.js',
       function: 'Object.generateSettingsXML',
       line: 362,
       method: 'generateSettingsXML',
       native: false },
     { column: 11,
       file: '/opt/PopcornTV/webserver.js',
       function: '',
       line: 475,
       method: null,
       native: false },
     { column: 17,
       file: 'events.js',
       function: 'Server.emit',
       line: 110,
       method: 'emit',
       native: false },
     { column: 12,
       file: '_http_server.js',
       function: 'HTTPParser.parserOnIncoming [as onIncoming]',
       line: 491,
       method: 'parserOnIncoming [as onIncoming]',
       native: false },
     { column: 23,
       file: '_http_common.js',
       function: 'HTTPParser.parserOnHeadersComplete',
       line: 111,
       method: 'parserOnHeadersComplete',
       native: false },
     { column: 22,
       file: '_http_server.js',
       function: 'Socket.socketOnData',
       line: 343,
       method: 'socketOnData',
       native: false } ],
  stack: 
   [ 'Error: Bad Parameter',
     '    at Error (native)',
     '    at strval (/opt/PopcornTV/node_modules/xml-writer/lib/xml-writer.js:19:14)',
     '    at Object.XMLWriter.text (/opt/PopcornTV/node_modules/xml-writer/lib/xml-writer.js:253:19)',
     '    at Object.XMLWriter.writeElement (/opt/PopcornTV/node_modules/xml-writer/lib/xml-writer.js:114:40)',
     '    at Object.generateSettingsXML (/opt/PopcornTV/XMLGenerator.js:362:34)',
     '    at Server.<anonymous> (/opt/PopcornTV/webserver.js:475:11)',
     '    at Server.emit (events.js:110:17)',
     '    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:491:12)',
     '    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)',
     '    at Socket.socketOnData (_http_server.js:343:22)' ] }
error: Error: Bad Parameter
    at Error (native)
    at strval (/opt/PopcornTV/node_modules/xml-writer/lib/xml-writer.js:19:14)
    at Object.XMLWriter.text (/opt/PopcornTV/node_modules/xml-writer/lib/xml-writer.js:253:19)
    at Object.XMLWriter.writeElement (/opt/PopcornTV/node_modules/xml-writer/lib/xml-writer.js:114:40)
    at Object.generateSettingsXML (/opt/PopcornTV/XMLGenerator.js:362:34)
    at Server.<anonymous> (/opt/PopcornTV/webserver.js:475:11)
    at Server.emit (events.js:110:17)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:491:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
    at Socket.socketOnData (_http_server.js:343:22)
```

But it definitely does seem to be better overall now that iojs isn't installed.
