### ISSUE TITLE
Unable to save favorites

### ISSUE THREAD

**Issue by acalatrava** [OstlerDev/PopcornTV#209]
Every time I try to add a favorite the server crashes:

error: There is an error checking favorites, please post this on the Github page
error:  TypeError: Cannot read property 'favorites' of undefined
    at Object.checkFavorite (/root/popcorntv/PopcornTV/settings.js:154:39)
    at Server.<anonymous> (/root/popcorntv/PopcornTV/webserver.js:465:39)
    at Server.EventEmitter.emit (events.js:98:17)
    at HTTPParser.parser.onIncoming (http.js:2076:12)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:120:23)
    at Socket.socket.ondata (http.js:1966:22)
    at TCP.onread (net.js:525:27)

**Comment by OstlerDev** [comment]
Could you post a full log?
Are you running the latest version?
Please run it in Debug mode and post a log.

**Comment by acalatrava** [comment]
Yes, I'm running latest version. I did a fresh reinstall of everything and it still failing.

Here is the full Debug log: http://pastebin.com/sQZrst1u

And this is the crash:
Debug: === Ending TVGrid.xml Generation ===
Debug: Query: {}
Web: /js/utils.js
Debug: Query: {"type":"tv","id":"tt0898266"}
error: There is an error checking favorites, please post this on the Github page
error:  TypeError: Cannot read property 'favorites' of undefined
    at Object.checkFavorite (/root/popcorntv/popcorn2/PopcornTV/settings.js:154:39)
    at Server.<anonymous> (/root/popcorntv/popcorn2/PopcornTV/webserver.js:465:39)
    at Server.EventEmitter.emit (events.js:98:17)
    at HTTPParser.parser.onIncoming (http.js:2076:12)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:120:23)
    at Socket.socket.ondata (http.js:1966:22)
    at TCP.onread (net.js:525:27)

It seems that in the line 465 of webserver.js:
      var checkFavorite = aTVSettings.checkFavorite(query.type, query.id, query.UDID);

query.UDID is undefined and that could be the cause

**Comment by OstlerDev** [comment]
It looks like you are running an Apple TV Version less then 6.0 is that correct?
