### ISSUE TITLE
PopcornTV node crashes!

### ISSUE THREAD

**Issue by losh11** [OstlerDev/PopcornTV#215]
I live in the UK, and as you may or may not know, lots of illegal websites (film streaming or torrenting) are blocked. And I believe this is what leads to the crashes. I'll explain in more detail.

As you open the trailers app with everything set up correctly, you are displayed with a choice for 'Films', 'TV' or 'Anime'. Everything in the Films section works fine. But as soon as you open the TV section, in terminal, atv.js crashes. This means I have to start it back up again by running ```sudo node atv.js```. This is the crash message I get:-

```
error: uncaughtException: Cannot read property 'replace' of undefined 
{ date: 'Tue Sep 01 2015 19:35:22 GMT+0100 (BST)',
  process: 
   { pid: 59503,
     uid: 0,
     gid: 0,
     cwd: '/Users/Loshan/Downloads/PopcornTV-0.2.1',
     execPath: '/usr/local/bin/node',
     version: 'v0.12.7',
     argv: [ 'node', '/Users/Loshan/Downloads/PopcornTV-0.2.1/atv.js' ],
     memoryUsage: { rss: 79826944, heapTotal: 59702528, heapUsed: 38856848 } },
  os: 
   { loadavg: [ 2.83935546875, 2.9873046875, 2.52587890625 ],
     uptime: 509957 },
  trace: 
   [ { column: 116,
       file: '/Users/Loshan/Downloads/PopcornTV-0.2.1/XMLGenerator.js',
       function: null,
       line: 1379,
       method: null,
       native: false },
     { column: 10,
       file: '/Users/Loshan/Downloads/PopcornTV-0.2.1/TVApi.js',
       function: 'Request._callback',
       line: 21,
       method: '_callback',
       native: false },
     { column: 22,
       file: '/Users/Loshan/Downloads/PopcornTV-0.2.1/node_modules/request/request.js',
       function: 'Request.self.callback',
       line: 368,
       method: 'self.callback',
       native: false },
     { column: 17,
       file: 'events.js',
       function: 'Request.emit',
       line: 110,
       method: 'emit',
       native: false },
     { column: 14,
       file: '/Users/Loshan/Downloads/PopcornTV-0.2.1/node_modules/request/request.js',
       function: '',
       line: 1219,
       method: null,
       native: false },
     { column: 20,
       file: 'events.js',
       function: 'Request.emit',
       line: 129,
       method: 'emit',
       native: false },
     { column: 12,
       file: '/Users/Loshan/Downloads/PopcornTV-0.2.1/node_modules/request/request.js',
       function: '',
       line: 1167,
       method: null,
       native: false },
     { column: 20,
       file: 'events.js',
       function: 'IncomingMessage.emit',
       line: 129,
       method: 'emit',
       native: false },
     { column: 16,
       file: '_stream_readable.js',
       function: null,
       line: 908,
       method: null,
       native: false },
     { column: 11,
       file: 'node.js',
       function: 'process._tickCallback',
       line: 355,
       method: '_tickCallback',
       native: false } ],
  stack: 
   [ 'TypeError: Cannot read property \'replace\' of undefined',
     '    at /Users/Loshan/Downloads/PopcornTV-0.2.1/XMLGenerator.js:1379:116',
     '    at Request._callback (/Users/Loshan/Downloads/PopcornTV-0.2.1/TVApi.js:21:10)',
     '    at Request.self.callback (/Users/Loshan/Downloads/PopcornTV-0.2.1/node_modules/request/request.js:368:22)',
     '    at Request.emit (events.js:110:17)',
     '    at Request.<anonymous> (/Users/Loshan/Downloads/PopcornTV-0.2.1/node_modules/request/request.js:1219:14)',
     '    at Request.emit (events.js:129:20)',
     '    at IncomingMessage.<anonymous> (/Users/Loshan/Downloads/PopcornTV-0.2.1/node_modules/request/request.js:1167:12)',
     '    at IncomingMessage.emit (events.js:129:20)',
     '    at _stream_readable.js:908:16',
     '    at process._tickCallback (node.js:355:11)' ] }
error: TypeError: Cannot read property 'replace' of undefined
    at /Users/Loshan/Downloads/PopcornTV-0.2.1/XMLGenerator.js:1379:116
    at Request._callback (/Users/Loshan/Downloads/PopcornTV-0.2.1/TVApi.js:21:10)
    at Request.self.callback (/Users/Loshan/Downloads/PopcornTV-0.2.1/node_modules/request/request.js:368:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/Users/Loshan/Downloads/PopcornTV-0.2.1/node_modules/request/request.js:1219:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/Users/Loshan/Downloads/PopcornTV-0.2.1/node_modules/request/request.js:1167:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

Similarly, I get an error if you select the 'Anime' section. This time, not in Terminal, but instead on the Apple TV. It says 'Trailer is unavailable'.

NOTE: Everything is running on root.

**Comment by OstlerDev** [comment]
Go into the Settings page, at the bottom you will see an option for TVApi Endpoint. Select that and set it to the UK TV Proxy :)

That should fix your error!

**Comment by OstlerDev** [comment]
@losh11 Did that work for you?

**Comment by losh11** [comment]
Just a second, someone is on the Apple TV right now.

**Comment by losh11** [comment]
It just says 'Accessing Trailers' when you change it and click on TV. And keeps on loading. Also the Anime section still says 'Trailers is unavailable. Try again later'.

This time, there is zero errors in Terminal though. It just looks like this:
![like this]
(http://i.imgur.com/RDndJBW.png)

**Comment by OstlerDev** [comment]
The Anime section has not been implemented, thus the error.

**Comment by losh11** [comment]
@OstlerDev But the TV section still doesn't work.

**Comment by OstlerDev** [comment]
Please follow this guide so I can further troubleshoot: https://github.com/OstlerDev/PopcornTV/wiki/How-to-report-an-issue

**Comment by OstlerDev** [comment]
@losh11 Are you still having issues?

**Comment by losh11** [comment]
Yes, will post log later. Currently a bit busy.
