### ISSUE TITLE
Error: Cannot find module 'ptv-images'

### ISSUE THREAD

**Issue by cristianciofu** [OstlerDev/PopcornTV#222]
Hello,

I have an error when I try to load a tv show page or the most recent movies : 

```
error: Error: Cannot find module 'ptv-images'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Applications/PopcornTV/fanartGenerator.js:1:76)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

I want to specify that I just updated today the app.

OS : OSX 10.10.4
Apple TV : ATV3

Thanks

**Comment by OstlerDev** [comment]
You need to run ``sudo npm install`` again when updating the application.

**Comment by cristianciofu** [comment]
Thanks @OstlerDev 

That was it...
