### ISSUE TITLE
Converting File..

### ISSUE THREAD

**Issue by domidyon** [OstlerDev/PopcornTV#225]
Hi!

Everytime I want to watch a show, I get stuck on ''Converting File...''
Error in terminal shows;

error: Error: spawn ffmpeg ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)

**Comment by OstlerDev** [comment]
Hi! Please follow this guide to install FFMPEG: https://github.com/OstlerDev/PopcornTV/wiki/How-to-install-FFMPEG
