### ISSUE TITLE
FFMPEG not working because of bad directory?

### ISSUE THREAD

**Issue by krugster** [OstlerDev/PopcornTV#229]
I have ffmpeg installed (correctly it seems?) but there is a problem when converting the file:
2015-09-13T00:55:30.961Z - notice: Starting PopcornTV
2015-09-13T00:55:30.966Z - DNS: DnsProxy binding on 192.168.1.200:53
2015-09-13T00:55:31.868Z - Web: listening on 192.168.1.200:80
2015-09-13T00:55:31.873Z - Web: SSL Web: listening on 192.168.1.200:443
2015-09-13T00:55:31.883Z - notice: Starting Commit 
2015-09-13T00:55:43.304Z - DNS: se-cdn.itunes-apple.com.akadns.net
2015-09-13T00:55:43.359Z - DNS: init-cdn.itunes-apple.com.akadns.net
2015-09-13T00:55:44.274Z - DNS: a4.mzstatic.com
2015-09-13T00:55:44.369Z - DNS: a1.mzstatic.com
2015-09-13T00:55:44.809Z - DNS: mzuserxp.itunes-apple.com.akadns.net
2015-09-13T00:55:44.844Z - DNS: pd-nk.itunes.apple.com
2015-09-13T00:55:45.399Z - Web: SSL: js/application.js
2015-09-13T00:55:45.699Z - Web: templates/navbar.xml
2015-09-13T00:55:45.799Z - Web: /js/utils.js
2015-09-13T00:55:45.819Z - Web: /js/navbarHandler.js
2015-09-13T00:55:45.929Z - Web: templates/index.xml
2015-09-13T00:55:45.994Z - Web: /js/utils.js
2015-09-13T00:55:46.279Z - DNS: configuration.apple.com
2015-09-13T00:55:48.524Z - Web: /Favorites.xml
2015-09-13T00:55:53.839Z - Web: /js/utils.js
2015-09-13T00:55:56.154Z - Web: /seasons.xml
2015-09-13T00:55:58.395Z - Web: /episodes.xml
2015-09-13T00:55:59.870Z - Web: /js/utils.js
2015-09-13T00:56:01.860Z - Web: /TVPrePlay.xml
2015-09-13T00:56:03.340Z - warning:  
{ type: 'TV',
  imdb: 'tt1553656',
  youtube: undefined,
  images: 
   { fanart: 'http://trailers.apple.com/cache/tt4484432-720.jpg',
     poster: 'https://walter.trakt.us/images/seasons/000/103/167/posters/original/5d65458b56.jpg' },
  related: 
   [ undefined,
     { title: 'Move On',
       subtitle: 'Episode 1',
       screenshot: 'https://walter.trakt.us/images/episodes/001/707/924/screenshots/thumb/d980e15d34.jpg' },
     undefined,
     { title: 'Redux',
       subtitle: 'Episode 3',
       screenshot: 'https://walter.trakt.us/images/episodes/001/766/182/screenshots/thumb/d29909a8e6.jpg' },
     { title: 'The Kinship',
       subtitle: 'Episode 4',
       screenshot: 'https://walter.trakt.us/images/episodes/001/766/183/screenshots/thumb/60bb30b312.jpg' },
     undefined,
     { title: 'Caged',
       subtitle: 'Episode 6',
       screenshot: 'https://walter.trakt.us/images/episodes/001/766/185/screenshots/thumb/280a9275d1.jpg' },
     { title: 'Ejecta',
       subtitle: 'Episode 7',
       screenshot: 'https://walter.trakt.us/images/episodes/001/766/186/screenshots/thumb/eeb4a9fd22.jpg' },
     { title: 'Breaking Point',
       subtitle: 'Episode 8',
       screenshot: 'https://walter.trakt.us/images/episodes/001/766/187/screenshots/thumb/f281ccd48f.jpg' },
     { title: 'Plan B',
       subtitle: 'Episode 9',
       screenshot: 'https://walter.trakt.us/images/episodes/001/766/188/screenshots/thumb/99e121a690.jpg' },
     { title: 'Legacy',
       subtitle: 'Episode 10',
       screenshot: 'https://walter.trakt.us/images/episodes/001/766/189/screenshots/thumb/ac48b726cf.jpg' },
     { title: 'Love is a Battlefield',
       subtitle: 'Episode 11',
       screenshot: 'https://walter.trakt.us/images/episodes/001/766/190/screenshots/thumb/09017d5a06.jpg' },
     { title: 'Incandescence',
       subtitle: 'Episode 12',
       screenshot: 'https://walter.trakt.us/images/episodes/001/766/191/screenshots/thumb/e9af0cc840.jpg' },
     { title: 'The Enemy Within',
       subtitle: 'Episode 13',
       screenshot: 'https://walter.trakt.us/images/episodes/001/766/192/screenshots/thumb/e04b59aa9d.jpg' } ],
  rating: 'TV-14',
  year: 'CBS',
  runtime: 45,
  genres: 
   [ 'crime',
     'drama',
     'mystery',
     'fantasy',
     'science-fiction',
     'horror' ],
  title: 'The Enemy Within',
  description: 'Series Finale- As the Dome in Chester\'s Mill comes down, the Resistance makes a final attempt to protect the outside world from the infected townspeople in the Kinship and their new queen.',
  rt_rating: 71,
  torrents: 
   { '0': 
      { peers: 0,
        seeds: 0,
        url: 'magnet:?xt=urn:btih:ad88408e78ec9b291cf0648cbfa62af8d88466be&dn=Under.the.Dome.S03E13.HDTV.x264-LOL.mp4%5Beztv%5D&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Fexodus.desync.com%3A6969' },
     '480p': 
      { peers: 0,
        seeds: 0,
        url: 'magnet:?xt=urn:btih:ad88408e78ec9b291cf0648cbfa62af8d88466be&dn=Under.the.Dome.S03E13.HDTV.x264-LOL.mp4%5Beztv%5D&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Fexodus.desync.com%3A6969' },
     '720p': 
      { peers: 0,
        seeds: 0,
        url: 'magnet:?xt=urn:btih:0cc484fc7143ad14b4fc5c5a30cc500d24d322be&dn=Under.the.Dome.S03E13.720p.HDTV.X264-DIMENSION.mkv%5Beztv%5D&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Fexodus.desync.com%3A6969' } } }
2015-09-13T00:56:03.530Z - Web: /js/utils.js
2015-09-13T00:56:03.715Z - Web: /thumbnails/MediaBadges/480p.png
2015-09-13T00:56:03.765Z - Web: /thumbnails/MediaBadges/720p.png
2015-09-13T00:56:03.870Z - Web: /thumbnails/MediaBadges/720p.png
2015-09-13T00:56:03.910Z - Web: /thumbnails/MediaBadges/480p.png
2015-09-13T00:56:05.146Z - Streamer: Streamer: Starting Stream... Please wait for stream to be ready.
2015-09-13T00:56:05.156Z - Web: /Movies/MoviePlay.xml
2015-09-13T00:56:05.336Z - Web: /js/play.js
2015-09-13T00:56:06.381Z - Web: /progress.json
2015-09-13T00:56:07.376Z - Web: /progress.json
2015-09-13T00:56:08.381Z - Web: /progress.json
2015-09-13T00:56:09.376Z - Web: /progress.json
2015-09-13T00:56:10.376Z - Web: /progress.json
2015-09-13T00:56:11.376Z - Web: /progress.json
2015-09-13T00:56:12.376Z - Web: /progress.json
2015-09-13T00:56:13.376Z - Web: /progress.json
2015-09-13T00:56:14.376Z - Web: /progress.json
2015-09-13T00:56:15.372Z - Web: /progress.json
2015-09-13T00:56:16.372Z - Web: /progress.json
2015-09-13T00:56:17.372Z - Web: /progress.json
2015-09-13T00:56:18.373Z - Web: /progress.json
2015-09-13T00:56:19.373Z - Web: /progress.json
2015-09-13T00:56:20.373Z - Web: /progress.json
2015-09-13T00:56:21.373Z - Web: /progress.json
2015-09-13T00:56:22.378Z - Web: /progress.json
2015-09-13T00:56:23.373Z - Web: /progress.json
2015-09-13T00:56:24.373Z - Web: /progress.json
2015-09-13T00:56:25.373Z - Web: /progress.json
2015-09-13T00:56:26.373Z - Web: /progress.json
2015-09-13T00:56:27.374Z - Web: /progress.json
2015-09-13T00:56:28.374Z - Web: /progress.json
2015-09-13T00:56:29.374Z - Web: /progress.json
2015-09-13T00:56:30.374Z - Web: /progress.json
2015-09-13T00:56:31.374Z - Web: /progress.json
2015-09-13T00:56:32.379Z - Web: /progress.json
2015-09-13T00:56:33.374Z - Web: /progress.json
2015-09-13T00:56:34.375Z - Web: /progress.json
2015-09-13T00:56:35.375Z - Web: /progress.json
2015-09-13T00:56:36.375Z - Web: /progress.json
2015-09-13T00:56:37.375Z - Web: /progress.json
2015-09-13T00:56:38.375Z - Web: /progress.json
2015-09-13T00:56:39.372Z - Web: /progress.json
2015-09-13T00:56:40.372Z - Web: /progress.json
2015-09-13T00:56:41.372Z - Web: /progress.json
2015-09-13T00:56:42.372Z - Web: /progress.json
2015-09-13T00:56:43.372Z - Web: /progress.json
2015-09-13T00:56:44.397Z - Web: /progress.json
2015-09-13T00:56:45.372Z - Web: /progress.json
2015-09-13T00:56:46.372Z - Web: /progress.json
2015-09-13T00:56:47.372Z - Web: /progress.json
2015-09-13T00:56:48.023Z - Streamer: Ready to Stream, binding to http://192.168.1.200:6169
2015-09-13T00:56:48.023Z - warning: =============== WARNING ===============
2015-09-13T00:56:48.023Z - warning: Attempting to convert non-supported file using FFMPEG.
2015-09-13T00:56:48.023Z - warning: This is VERY Unstable and most likely WILL NOT WORK!
2015-09-13T00:56:48.023Z - warning: =======================================
2015-09-13T00:56:48.055Z - error: uncaughtException: ENOENT, no such file or directory 'C:\Windows\system32\assets\torrent-stream\0cc484fc7143ad14b4fc5c5a30cc500d24d322be' 
{ date: 'Sat Sep 12 2015 17:56:48 GMT-0700 (Pacific Daylight Time)',
  process: 
   { pid: 4708,
     uid: null,
     gid: null,
     cwd: 'C:\\Windows\\system32',
     execPath: 'C:\\Program Files (x86)\\nodejs\\node.exe',
     version: 'v0.12.7',
     argv: 
      [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
        'C:\\Users\\pkrug\\PopcornTV\\atv.js' ],
     memoryUsage: { rss: 95940608, heapTotal: 43419136, heapUsed: 20778652 } },
  os: { loadavg: [ 0, 0, 0 ], uptime: 224668.6952963 },
  trace: 
   [ { column: null,
       file: null,
       function: 'Error',
       line: null,
       method: null,
       native: true },
     { column: 18,
       file: 'fs.js',
       function: 'Object.fs.readdirSync',
       line: 761,
       method: 'fs.readdirSync',
       native: false },
     { column: 6,
       file: 'C:\\Users\\pkrug\\PopcornTV\\webserver.js',
       function: 'convertFile',
       line: 748,
       method: null,
       native: false },
     { column: 11,
       file: 'C:\\Users\\pkrug\\PopcornTV\\webserver.js',
       function: '',
       line: 90,
       method: null,
       native: false },
     { column: 20,
       file: 'events.js',
       function: 'emit',
       line: 129,
       method: null,
       native: false },
     { column: 22,
       file: 'C:\\Users\\pkrug\\PopcornTV\\streamer-server.js',
       function: '',
       line: 65,
       method: null,
       native: false },
     { column: 17,
       file: 'events.js',
       function: 'TorrentStreamer.emit',
       line: 107,
       method: 'emit',
       native: false },
     { column: 8,
       file: 'C:\\Users\\pkrug\\PopcornTV\\lib\\streamers\\base.js',
       function: '',
       line: 60,
       method: null,
       native: false },
     { column: 17,
       file: 'events.js',
       function: 'Through2.emit',
       line: 107,
       method: 'emit',
       native: false },
     { column: 6,
       file: 'C:\\Users\\pkrug\\PopcornTV\\node_modules\\progress-stream\\index.js',
       function: 'emit',
       line: 36,
       method: null,
       native: false } ],
  stack: 
   [ 'Error: ENOENT, no such file or directory \'C:\\Windows\\system32\\assets\\torrent-stream\\0cc484fc7143ad14b4fc5c5a30cc500d24d322be\'',
     '    at Error (native)',
     '    at Object.fs.readdirSync (fs.js:761:18)',
     '    at convertFile (C:\\Users\\pkrug\\PopcornTV\\webserver.js:748:6)',
     '    at null.<anonymous> (C:\\Users\\pkrug\\PopcornTV\\webserver.js:90:11)',
     '    at emit (events.js:129:20)',
     '    at TorrentStreamer.<anonymous> (C:\\Users\\pkrug\\PopcornTV\\streamer-server.js:65:22)',
     '    at TorrentStreamer.emit (events.js:107:17)',
     '    at Through2.<anonymous> (C:\\Users\\pkrug\\PopcornTV\\lib\\streamers\\base.js:60:8)',
     '    at Through2.emit (events.js:107:17)',
     '    at emit (C:\\Users\\pkrug\\PopcornTV\\node_modules\\progress-stream\\index.js:36:6)' ] }
2015-09-13T00:56:48.060Z - error: Error: ENOENT, no such file or directory 'C:\Windows\system32\assets\torrent-stream\0cc484fc7143ad14b4fc5c5a30cc500d24d322be'
    at Error (native)
    at Object.fs.readdirSync (fs.js:761:18)
    at convertFile (C:\Users\pkrug\PopcornTV\webserver.js:748:6)
    at null.<anonymous> (C:\Users\pkrug\PopcornTV\webserver.js:90:11)
    at emit (events.js:129:20)
    at TorrentStreamer.<anonymous> (C:\Users\pkrug\PopcornTV\streamer-server.js:65:22)
    at TorrentStreamer.emit (events.js:107:17)
    at Through2.<anonymous> (C:\Users\pkrug\PopcornTV\lib\streamers\base.js:60:8)
    at Through2.emit (events.js:107:17)
    at emit (C:\Users\pkrug\PopcornTV\node_modules\progress-stream\index.js:36:6)
2015-09-13T00:56:48.375Z - Web: /progress.json
2015-09-13T00:56:49.375Z - Web: /progress.json
2015-09-13T00:56:50.375Z - Web: /progress.json
2015-09-13T00:56:51.375Z - Web: /progress.json
2015-09-13T00:56:52.375Z - Web: /progress.json
2015-09-13T00:56:53.375Z - Web: /progress.json

**Comment by krugster** [comment]
I checked the filesystem and that path does exist: C:\Windows\system32\assets\torrent-stream\0cc484fc7143ad14b4fc5c5a30cc500d24d322be.  It is both a directory and a torrent file by the same name

**Comment by krugster** [comment]
It starts the download and then the ATV goes to "converting file" and just sits there indefinitely.

**Comment by OstlerDev** [comment]
Hmm... It looks like someone else reported this as well, when I get some time I will look into it :)
