### ISSUE TITLE
trailers stuck accessing popcorn tv

### ISSUE THREAD

**Issue by akpasumarthi** [OstlerDev/PopcornTV#244]
Apple tv stuck accessing the Popcorn and and everytime I access any movie thumbnail. I am seeing the following error.

My node is running on windows 10 with nodejs version 4.1.2

Web: /Movies/MoviePrePlay.xml
error: uncaughtException: Can't load the addon. Issue to: https://github.com/PopcornTV/node-images/issues
{ date: 'Sun Oct 11 2015 10:16:18 GMT-0400 (Eastern Daylight Time)',
  process:
   { pid: 13428,
     uid: null,
     gid: null,
     cwd: 'C:\\Users\\akpasumarthi\\PopcornTV',
     execPath: 'C:\\Program Files\\nodejs\\node.exe',
     version: 'v4.1.2',
     argv:
      [ 'C:\\Program Files\\nodejs\\node.exe',
        'C:\\Users\\akpasumarthi\\PopcornTV\\atv.js' ],
     memoryUsage: { rss: 55169024, heapTotal: 38133504, heapUsed: 26702592 } },
  os: { loadavg: [ 0, 0, 0 ], uptime: 1692445.3432507 },
  trace:
   [ { column: 7,
       file: 'C:\\Users\\akpasumarthi\\PopcornTV\\node_modules\\ptv-images\\binding.js',
       function: '',
       line: 61,
       method: null,
       native: false },
     { column: 26,
       file: 'module.js',
       function: 'Module._compile',
       line: 434,
       method: '_compile',
       native: false },
     { column: 10,
       file: 'module.js',
       function: 'Object.Module._extensions..js',
       line: 452,
       method: 'Module._extensions..js',
       native: false },
     { column: 32,
       file: 'module.js',
       function: 'Module.load',
       line: 355,
       method: 'load',
       native: false },
     { column: 12,
       file: 'module.js',
       function: 'Function.Module._load',
       line: 310,
       method: 'Module._load',
       native: false },
     { column: 17,
       file: 'module.js',
       function: 'Module.require',
       line: 365,
       method: 'require',
       native: false },
     { column: 17,
       file: 'module.js',
       function: 'require',
       line: 384,
       method: null,
       native: false },
     { column: 15,
       file: 'C:\\Users\\akpasumarthi\\PopcornTV\\node_modules\\ptv-images\\index.js',
       function: '',
       line: 4,
       method: null,
       native: false },
     { column: 26,
       file: 'module.js',
       function: 'Module._compile',
       line: 434,
       method: '_compile',
       native: false },
     { column: 10,
       file: 'module.js',
       function: 'Object.Module._extensions..js',
       line: 452,
       method: 'Module._extensions..js',
       native: false } ],
  stack:
   [ 'Error: Can\'t load the addon. Issue to: https://github.com/PopcornTV/node-images/issues',
     '    at Object.<anonymous> (C:\\Users\\akpasumarthi\\PopcornTV\\node_modules\\ptv-images\\binding.js:61:7)
',
     '    at Module._compile (module.js:434:26)',
     '    at Object.Module._extensions..js (module.js:452:10)',
     '    at Module.load (module.js:355:32)',
     '    at Function.Module._load (module.js:310:12)',
     '    at Module.require (module.js:365:17)',
     '    at require (module.js:384:17)',
     '    at Object.<anonymous> (C:\\Users\\akpasumarthi\\PopcornTV\\node_modules\\ptv-images\\index.js:4:15)',

     '    at Module._compile (module.js:434:26)',
     '    at Object.Module._extensions..js (module.js:452:10)' ] }
error: Error: Can't load the addon. Issue to: https://github.com/PopcornTV/node-images/issues
    at Object.<anonymous> (C:\Users\akpasumarthi\PopcornTV\node_modules\ptv-images\binding.js:61:7)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\akpasumarthi\PopcornTV\node_modules\ptv-images\index.js:4:15)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)

**Comment by poloh11** [comment]
I have the same issue on my Windows 7

**Comment by cprzytocki** [comment]
I'm having the same issue on OS maverick

**Comment by cprzytocki** [comment]
I'm having the same issue os OS X Yosemite

**Comment by OstlerDev** [comment]
@akpasumarthi @poloh11 @cprzytocki Please downgrade to Node v0.12.x I am working on adding support for Node 4.x.x but it is NOT working yet.

**Comment by cprzytocki** [comment]
@OstlerDev Not sure if this is because of the node version I'm using (0.12.7) but when popcorntv is "Converting File..." this error comes up
error: Error: spawn ffmpeg ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)

**Comment by OstlerDev** [comment]
@cprzytocki when you get that error you need to install FFMPEG. For instructions on how to install please check the Wiki.
