### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by cianf123** [OstlerDev/PopcornTV#245]
Having this error when attempting the final phase of the commads

C:\Users\Cian\Desktop\PopcornTV-master>node atv.js
notice: Starting PopcornTV
DNS: DnsProxy binding on 192.168.192.14:53
error: There is an error starting Popcorn TV, please post this on the Github page
error: Error: Cannot find module 'domhandler'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\Cian\Desktop\PopcornTV-master\node_modules\ytdl-core\node_modules\cheerio\node_modules\htmlparser2\lib\index.js:2:18)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)

Dont really know where to go from there.

**Comment by masonjames** [comment]
Try running npm install again - even going to the C:\Users\Cian\Desktop\PopcornTV-master\node_modules\ytdl-core\node_modules\cheerio\node_modules\htmlparser2 and running npm install in that directory specifically.

Let us know how it goes!
