### ISSUE TITLE
Getting error when opening movies/tvshows

### ISSUE THREAD

**Issue by cprzytocki** [OstlerDev/PopcornTV#249]
The screen is stuck at accessing trailers and this error is shown in terminal (OS X Yosemite)

error: TypeError: Cannot read property 'data' of undefined
    at Request._callback (/Users/christopherprzytocki/Desktop/PopcornTV/MoviesAPI.js:14:27)
    at Request.self.callback (/Users/christopherprzytocki/Desktop/PopcornTV/node_modules/request/request.js:368:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/Users/christopherprzytocki/Desktop/PopcornTV/node_modules/request/request.js:1219:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/Users/christopherprzytocki/Desktop/PopcornTV/node_modules/request/request.js:1167:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

**Comment by OstlerDev** [comment]
The place we get our Movies and TV shows from are currently offline. There is nothing we can do about this.
