### ISSUE TITLE
yts.to

### ISSUE THREAD

**Issue by FabianoFrota** [OstlerDev/PopcornTV#255]
Error when trying to connect to https://yts.to/api/v2/list_movies.json?sort_by=seeds&limit=50&page=1

**Comment by JakeRound** [comment]
yts.to no longer exists as it was taken down however if you open 
MoviesAPI.js 
Edit line 6 and replace it with the following

var url = "https://yts.ag/api/v2/list_movies.json?sort_by=" + sort_by + "&limit=" + amount + "&page=" + page;

Hope it helps!

**Comment by FabianoFrota** [comment]
Sweet! But other error

error: Error: Can't load the addon. Issue to: https://github.com/PopcornTV/node-images/issues
    at Object.<anonymous> (/Users/macbook/Desktop/PopcornTV/node_modules/ptv-images/binding.js:61:7)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/macbook/Desktop/PopcornTV/node_modules/ptv-images/index.js:4:15)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)

**Comment by JakeRound** [comment]
There's a phrasing error when pasting. Basically revert to stock file and change the domain from YTS.to so it's YTS.ag, There's no copy and pasting to cause a phrasing error doing it that way my apologises

I don't use this application anymore since i've got an Apple TV 4

**Comment by hugge1818** [comment]
@JakeRound still getting that error
