### ISSUE TITLE
Error connecting to trakt.tv and grabbing json

### ISSUE THREAD

**Issue by soavarice** [OstlerDev/PopcornTV#256]
2015-12-25T13:49:50.865Z - warning: Error connecting to trakt.tv and grabbing json: https://api-v2launch.trakt.tv/movies/undefined?extended=images

Hi i cant get the im error in MoviesAPi.js when im trying to go in movie description.

Can find 'imdb'

Here is the line:

var url = 'https://api-v2launch.trakt.tv/movies/' + imdb + '?extended=images';

I fixed myself the MovieAPIs/TVAPIs to other, but cant start the movies. TVs are OK

**Comment by hugge1818** [comment]
same for me too

**Comment by hugge1818** [comment]
@soavarice

**Comment by hugge1818** [comment]
![skarmklipp8](https://cloud.githubusercontent.com/assets/16634417/12460941/99ee46b0-bfb6-11e5-975c-c610516c66b6.PNG)

**Comment by hugge1818** [comment]
@OstlerDev do u have any suggestions

**Comment by OstlerDev** [comment]
It would be happening because whatever API is being used does not provide an IMDB code, when it says `undefined

**Comment by hugge1818** [comment]
@OstlerDev Can it get fixed

**Comment by OstlerDev** [comment]
That is not something that is wrong on my end, that is something that is wrong with your end. I assume it would be an issue if you are using yify.is as I believe their API is different, however from what I saw the yts.ag API is exactly the same as the old yts.

I cannot comment on how to modify the old API to the new one sadly. Best of luck to you.

**Comment by hugge1818** [comment]
@OstlerDev i am using yts.ag

**Comment by soavarice** [comment]
Thanks, OstlerDev. I also used yts.ag.

**Comment by hugge1818** [comment]
thank for explaning @OstlerDev

**Comment by hugge1818** [comment]
@OstlerDev I have changed my computer and reset evrything on the new and i am get same error (followed the instruction how to install it and getting the same error). @soavarice Did u find a solution on the problem?

**Comment by joshtylerclarke** [comment]
I joined GitHub specifically to comment on this. I am having the same issue. Would either @soavarice or @hugge1818 like to create a repository where we can collaborate? Is it possible @OstlerDev's trakt.tv API key is expired or invalid?

**Comment by OstlerDev** [comment]
![](http://i.imgur.com/L0QBVFA.png)

**Comment by joshtylerclarke** [comment]
@OstlerDev, can you tell us where/how the var imdb is first established in the code ... ?

**Comment by OstlerDev** [comment]
There are a couple places, but this should be the root of it that you can trace with: 

https://github.com/OstlerDev/PopcornTV/blob/master/MoviesAPI.js#L60

**Comment by soavarice** [comment]
I think its not the this IMDB code, because Popcorn Time use the same code/var and he is working with YTS.ag/YIFI.is

Also, like my original post - 'TVs are OK' and they use the same code? Or im wrong.

**Comment by joshtylerclarke** [comment]
TV is working for me too using the onion.to tv api ... Maybe the yts api is the problem ...

**Comment by soavarice** [comment]
Yep, my bad. But still, popcorn time use the same code and working.

**Comment by joshtylerclarke** [comment]
I think the difference is that if PopcornTime can't get an IMDB id, it will just continue loading without art, synopsis, etc.

PopcornTV requires the ids or it crashes.

**Comment by OstlerDev** [comment]
There was a catch put in that was meant to prevent it, but I must have done it wrong. Just go into the settings and disable fanart.

**Comment by joshtylerclarke** [comment]
Try this ...

[MoviesAPI.js](http://s000.tinyupload.com/download.php?file_id=15681586693279529046&t=1568158669327952904635914)

**Comment by joshtylerclarke** [comment]
Now when it gets to buffering, I get this:

    Streamer: Streamer: Starting Stream... Please wait for stream to be ready.
Web: /Movies/MoviePlay.xml
Web: /js/play.js
error: uncaughtException: Invalid torrent identifier 
{ date: 'Sun Jan 24 2016 04:03:45 GMT-0800 (PST)',
  process: 
   { pid: 6638,
     uid: 0,
     gid: 0,
     cwd: '/Users/Josh/Documents/PopcornTV',
     execPath: '/usr/local/bin/node',
     version: 'v0.12.9',
     argv: [ 'node', '/Users/Josh/Documents/PopcornTV/atv.js' ],
     memoryUsage: { rss: 229933056, heapTotal: 75145472, heapUsed: 29592168 } },
  os: 
   { loadavg: [ 0.97119140625, 1.14794921875, 1.275390625 ],
     uptime: 180189 },
  trace: 
   [ { column: 11,
       file: '/Users/Josh/Documents/PopcornTV/node_modules/read-torrent/node_modules/parse-torrent/index.js',
       function: 'parseTorrent',
       line: 27,
       method: null,
       native: false },
     { column: 26,
       file: '/Users/Josh/Documents/PopcornTV/node_modules/read-torrent/index.js',
       function: 'onData',
       line: 25,
       method: null,
       native: false },
     { column: 9,
       file: '/Users/Josh/Documents/PopcornTV/node_modules/read-torrent/index.js',
       function: 'Request.onResponse [as _callback]',
       line: 47,
       method: 'onResponse [as _callback]',
       native: false },
     { column: 22,
       file: '/Users/Josh/Documents/PopcornTV/node_modules/read-torrent/node_modules/request/index.js',
       function: 'Request.self.callback',
       line: 142,
       method: 'self.callback',
       native: false },
     { column: 17,
       file: 'events.js',
       function: 'Request.emit',
       line: 110,
       method: 'emit',
       native: false },
     { column: 14,
       file: '/Users/Josh/Documents/PopcornTV/node_modules/read-torrent/node_modules/request/index.js',
       function: '',
       line: 856,
       method: null,
       native: false },
     { column: 20,
       file: 'events.js',
       function: 'Request.emit',
       line: 129,
       method: 'emit',
       native: false },
     { column: 12,
       file: '/Users/Josh/Documents/PopcornTV/node_modules/read-torrent/node_modules/request/index.js',
       function: '',
       line: 808,
       method: null,
       native: false },
     { column: 20,
       file: 'events.js',
       function: 'IncomingMessage.emit',
       line: 129,
       method: 'emit',
       native: false },
     { column: 16,
       file: '_stream_readable.js',
       function: null,
       line: 908,
       method: null,
       native: false } ],
  stack: 
   [ 'Error: Invalid torrent identifier',
     '    at parseTorrent (/Users/Josh/Documents/PopcornTV/node_modules/read-torrent/node_modules/parse-torrent/index.js:27:11)',
     '    at onData (/Users/Josh/Documents/PopcornTV/node_modules/read-torrent/index.js:25:26)',
     '    at Request.onResponse [as _callback] (/Users/Josh/Documents/PopcornTV/node_modules/read-torrent/index.js:47:9)',
     '    at Request.self.callback (/Users/Josh/Documents/PopcornTV/node_modules/read-torrent/node_modules/request/index.js:142:22)',
     '    at Request.emit (events.js:110:17)',
     '    at Request.<anonymous> (/Users/Josh/Documents/PopcornTV/node_modules/read-torrent/node_modules/request/index.js:856:14)',
     '    at Request.emit (events.js:129:20)',
     '    at IncomingMessage.<anonymous> (/Users/Josh/Documents/PopcornTV/node_modules/read-torrent/node_modules/request/index.js:808:12)',
     '    at IncomingMessage.emit (events.js:129:20)',
     '    at _stream_readable.js:908:16' ] }
error: Error: Invalid torrent identifier
    at parseTorrent (/Users/Josh/Documents/PopcornTV/node_modules/read-torrent/node_modules/parse-torrent/index.js:27:11)
    at onData (/Users/Josh/Documents/PopcornTV/node_modules/read-torrent/index.js:25:26)
    at Request.onResponse [as _callback] (/Users/Josh/Documents/PopcornTV/node_modules/read-torrent/index.js:47:9)
    at Request.self.callback (/Users/Josh/Documents/PopcornTV/node_modules/read-torrent/node_modules/request/index.js:142:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/Users/Josh/Documents/PopcornTV/node_modules/read-torrent/node_modules/request/index.js:856:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/Users/Josh/Documents/PopcornTV/node_modules/read-torrent/node_modules/request/index.js:808:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json
Web: /progress.json

**Comment by soavarice** [comment]
What is this APIs server? your own?

**Comment by hugge1818** [comment]
@soavarice yes what do u think?

**Comment by joshtylerclarke** [comment]
This is the API included in the popcorntime.io vpn.ht hotfix.

**Comment by soavarice** [comment]
I think the problem is that, script cant dowload or reach the torrent.

Simple link from a API for the torrent file - http://62.210.81.37/torrent/download/8D4861A87BF6093D24E720D34EF6BB158E8C15BA.torrent

Doesnt work.

If you try with YTS.ag its working - https://yts.ag/torrent/download/2F06CC1284C786BB7A8C6F0F493D6E3A65A784D2.torrent

**Comment by soavarice** [comment]
Can the problem with YTS.ag is that they dont have a 'rt_audience_score' in movie_details API? Here the fanart and there is 'rt_audience_score' @OstlerDev ?


function getMovieWithFanart(torrentID, resolution, callback) {
	var page = 1;
	var request = require("request")

	var url = "https://yts.ag/api/v2/movie_details.json?with_images=true&with_cast=true&movie_id=" + torrentID;
	logger.Debug("=== Getting Movie ===");
	logger.Debug(url);
	request({
	    url: url,
	    json: true
	}, function (error, response, body) {
 	   if (!error && response.statusCode === 200) {
	        var movie = body.data;
	        logger.Debug(movie);
	        var Fan = require('./fanartGenerator')
	        try {
	        	Fan.generateFanart(movie.imdb_code, resolution, function(url){
					callback(movie, url);
				});
	        } catch(e) {
	        	movie['rt_audience_score'] = '50';
	        	callback(movie, 'thumbnails/Background_blank_1080.jpg');
	        }
	    } else {
			logger.warning("Error connecting to yts.ag and grabbing json: " + url);
			return;
	    }
	})
}

**Comment by soavarice** [comment]
Its now all working with @joshtylerclarke MoviesAPI.js !

**Comment by hugge1818** [comment]
@soavarice Did it fix when u changed require to request? Or did he Chang in his api so it worked?

**Comment by soavarice** [comment]
@hugge1818 just download the MoviesAPI.js from @joshtylerclarke comment or download all files from my repo - https://github.com/soavarice/PopcornTV

Also i make a pull request, only @OstlerDev need to accept.

**Comment by hugge1818** [comment]
Thanks so much  @soavarice and @joshtylerclarke
Haven't test it get but hopfully it's working

**Comment by hugge1818** [comment]
Hopefully*

**Comment by joshtylerclarke** [comment]
@soavarice I have uninstalled this as I had all but given up. Are you saying that by using my MoviesAPI without any other change to code, the app is working now? Because it wasn't working before. That would imply that someone changed a setting in the API ...

I am in no way connected with the API, other than that I found it in the code of the vpn.ht update for popcorn time.io

**Comment by hugge1818** [comment]
@soavarice and @joshtylerclarke thanks it worked love it, thanks so much again!!!

**Comment by hugge1818** [comment]
@joshtylerclarke just download @soavarice repo above

**Comment by soavarice** [comment]
Yep @joshtylerclarke , but for better just download from my repo. For me and @hugge1818 is working like charm. Also TVs api is update with better one.

**Comment by joshtylerclarke** [comment]
Woohoo! It's working!
