### ISSUE TITLE
Crash on Null Returns from TraktTV

### ISSUE THREAD

**Issue by OstlerDev** [OstlerDev/PopcornTV#31]
Attempting to load a null movie poster will crash the application. Full log of the error below.

```
Debug: === Starting TVGrid.xml Generation ===
Debug: Query: {"imdb":"tt3007640","title":"Naked and Afraid"}
Debug: === Starting seasons.xml Generation ===
Debug: === Getting Seasons ===
Debug: https://api-v2launch.trakt.tv/shows/tt3007640/seasons?extended=images
Web: /seasons.xml
DNS: e5153.a.akamaiedge.net
Debug:  
{ '0': 
   { number: 1,
     ids: { trakt: 60881, tvdb: null, tmdb: null, tvrage: null },
     images: 
      { poster: 
         { full: 'https://walter.trakt.us/images/seasons/000/060/881/posters/original/d1011059d3.jpg',
           medium: 'https://walter.trakt.us/images/seasons/000/060/881/posters/medium/d1011059d3.jpg',
           thumb: 'https://walter.trakt.us/images/seasons/000/060/881/posters/thumb/d1011059d3.jpg' },
        thumb: { full: null } } },
  '1': 
   { number: 0,
     ids: { trakt: 101817, tvdb: null, tmdb: null, tvrage: null },
     images: 
      { poster: { full: null, medium: null, thumb: null },
        thumb: { full: null } } },
  '2': 
   { number: 2,
     ids: { trakt: 101819, tvdb: null, tmdb: null, tvrage: null },
     images: 
      { poster: 
         { full: 'https://walter.trakt.us/images/seasons/000/101/819/posters/original/971ac68a48.jpg',
           medium: 'https://walter.trakt.us/images/seasons/000/101/819/posters/medium/971ac68a48.jpg',
           thumb: 'https://walter.trakt.us/images/seasons/000/101/819/posters/thumb/971ac68a48.jpg' },
        thumb: { full: null } } },
  '3': 
   { number: 3,
     ids: { trakt: 101823, tvdb: null, tmdb: null, tvrage: null },
     images: 
      { poster: 
         { full: 'https://walter.trakt.us/images/seasons/000/101/823/posters/original/832c571f6a.jpg',
           medium: 'https://walter.trakt.us/images/seasons/000/101/823/posters/medium/832c571f6a.jpg',
           thumb: 'https://walter.trakt.us/images/seasons/000/101/823/posters/thumb/832c571f6a.jpg' },
        thumb: { full: null } } },
  '4': 
   { number: 4,
     ids: { trakt: 107493, tvdb: null, tmdb: null, tvrage: null },
     images: 
      { poster: { full: null, medium: null, thumb: null },
        thumb: { full: null } } } }
Debug: === Getting Fanart ===
Debug: https://api-v2launch.trakt.tv/shows/tt3007640?extended=images
Debug: https://walter.trakt.us/images/shows/000/058/445/fanarts/original/cfeccc090a.jpg
Debug: === Generating Fanart for TV ===
Debug: === Getting Season Numbers ===
Debug: http://eztvapi.re/show/tt3007640
Debug:  
{ '0': 1, '1': 2, '2': 3, '3': 4 }
/Users/sky/Desktop/PopcornTV/node_modules/xml-writer/lib/xml-writer.js:19
  else throw Error('Bad Parameter');
       ^
Error: Bad Parameter
    at Error (native)
    at strval (/Users/sky/Desktop/PopcornTV/node_modules/xml-writer/lib/xml-writer.js:19:14)
    at Object.XMLWriter.text (/Users/sky/Desktop/PopcornTV/node_modules/xml-writer/lib/xml-writer.js:253:19)
    at Object.XMLWriter.writeElement (/Users/sky/Desktop/PopcornTV/node_modules/xml-writer/lib/xml-writer.js:114:40)
    at /Users/sky/Desktop/PopcornTV/XMLGenerator.js:475:8
    at /Users/sky/Desktop/PopcornTV/TVApi.js:73:12
    at Request._callback (/Users/sky/Desktop/PopcornTV/TVApi.js:261:10)
    at Request.self.callback (/Users/sky/Desktop/PopcornTV/node_modules/request/request.js:368:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/Users/sky/Desktop/PopcornTV/node_modules/request/request.js:1219:14)
```

**Comment by OstlerDev** [comment]
Fixed in: 6f65efabbca997d3adae3563fbd1f31ee1354f23
