### ISSUE TITLE
can not start popcorntv

### ISSUE THREAD

**Issue by b2grcn** [OstlerDev/PopcornTV#56]
hi. i started popcorntv but took the error code as below.

DNS: DnsProxy binding on 192.168.0.10:53
Web: listening on 192.168.0.10:80
Web: SSL Web: listening on 192.168.0.10:443
Web: SSL: js/application.js
Web: templates/navbar.xml
Web: /js/utils.js
Web: /js/navbarHandler.js
Web: templates/index.xml
Web: /js/utils.js
Web: /Parade.xml
DNS: e5153.a.akamaiedge.net
Web: templates/MovieNav.xml
Web: /js/utils.js
Web: /js/navbarHandler.js
Web: /MoviesGrid.xml
Web: /js/utils.js
error: There is an error checking settings, please post this on the Github page
error:  SyntaxError: Unexpected end of input
    at Object.parse (native)
    at Object.checkSetting (/Users/gurcanaydn/Desktop/PopcornTV/settings.js:183:29)
    at Server.<anonymous> (/Users/gurcanaydn/Desktop/PopcornTV/webserver.js:148:29)
    at Server.emit (events.js:110:17)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:491:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
    at Socket.socketOnData (_http_server.js:343:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)

**Comment by OstlerDev** [comment]
Please report the issue with the correct formatting: https://github.com/OstlerDev/PopcornTV/wiki/How-to-report-an-issue

Can you reproduce this issue? If so, how?

**Comment by b2grcn** [comment]
it worked. thanks

**Comment by OstlerDev** [comment]
Glad to hear that it worked for you!
