### ISSUE TITLE
PopcornTV crashes

### ISSUE THREAD

**Issue by freestylemaster** [OstlerDev/PopcornTV#57]
On Debian 8, as soon as I hit play button I end up with below error;

Streamer: Streamer: Starting Stream... Please wait for stream to be ready.
Web: /Movies/MoviePlay.xml
Streamer: Ready to Stream, binding to http://10.0.1.110:9999
module.js:338
    throw err;
          ^
Error: Cannot find module 'xmlrpc'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/root/PopcornTV/SubtitleAPI.js:5:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

**Comment by farcaller** [comment]
See #55
