### ISSUE TITLE
Error: Cannot find module 'file-type'

### ISSUE THREAD

**Issue by pitercio** [OstlerDev/PopcornTV#58]
Just trying to test the new subtitles, I got this error:

error: There is an error starting Popcorn TV, please post this on the Github page
error:  Error: Cannot find module 'file-type'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/gerardosanchezortega/Desktop/PopcornTV/streamer-server.js:14:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

I can see that you are updating some files here, I hope it's something related to a bad/incomplete git sync :)

Thank you!!

**Comment by OstlerDev** [comment]
You need to re-run 'npm install'

There is also a major issue with OpenSubtitles currently as they changed their API last night right after I implemented it. This means that we cannot currently pull most subtitles down.

**Comment by pitercio** [comment]
Done. It starts nicely, but...

DNS: DnsProxy binding on 192.168.1.105:53
Web: listening on 192.168.1.105:80
Web: SSL Web: listening on 192.168.1.105:443
DNS: local
DNS: apple.com
Web: SSL: js/application.js
Web: templates/navbar.xml
Web: /js/utils.js
Web: /js/navbarHandler.js
Web: templates/index.xml
Web: /js/utils.js
Web: /Parade.xml
DNS: s.ynet.io
Web: templates/Search/search.xml
error: There is an error loading settings, please post this on the Github page
error:  SyntaxError: Unexpected token “
    at Object.parse (native)
    at Object.loadSettings (/Users/gerardosanchezortega/Desktop/PopcornTV/settings.js:29:29)
    at Object.generateSettingsXML (/Users/gerardosanchezortega/Desktop/PopcornTV/XMLGenerator.js:277:29)
    at Server.<anonymous> (/Users/gerardosanchezortega/Desktop/PopcornTV/webserver.js:326:8)
    at Server.emit (events.js:110:17)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:491:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
    at Socket.socketOnData (_http_server.js:343:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
/Users/gerardosanchezortega/Desktop/PopcornTV/XMLGenerator.js:330
	.writeAttribute('onSelect', "toggleSetting('quality', '" + settings.quality +
	                                                                   ^
TypeError: Cannot read property 'quality' of undefined
    at Object.generateSettingsXML (/Users/gerardosanchezortega/Desktop/PopcornTV/XMLGenerator.js:330:81)
    at Server.<anonymous> (/Users/gerardosanchezortega/Desktop/PopcornTV/webserver.js:326:8)
    at Server.emit (events.js:110:17)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:491:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
    at Socket.socketOnData (_http_server.js:343:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)

Any clue?

**Comment by pitercio** [comment]
... and, about the OpenSubtitles API change... terrific timing!!

**Comment by OstlerDev** [comment]
Try closing and restarting it and see if that helps. For some reason it is thinking that the settings file is not being created.

Yep, I implemented it, then not even 30 minutes later the server goes down and they break it.
