### ISSUE TITLE
Run PopCornTV on ubuntu server with apache

### ISSUE THREAD

**Issue by brunojalves** [OstlerDev/PopcornTV#71]
Hi,

Just one thing, can i set up the PopCornTV to run on a single ip?

So my problem is i have an ubuntu server running on home,and i would like to run PopCornTV on it, but i'm stuck.

I can set up 2 ip on this server eth0((removed).199) and eth0:1((removed).200), and run apache on only one ip:
netstat -nap | grep :80
tcp        0      0  (removed):80        0.0.0.0:*               LISTEN      15942/apache2 

so i change the config.json to run on eth0:1(192.168.7.200).

But i can't start the PopCornTV
node atv.js
notice: Starting PopcornTV
DNS: DnsProxy binding on (removed):53
Web: listening on (removed):80
Web: SSL Web: listening on (removed):443
error: ========= FATAL ERROR =========
error: Cannot bind to Port 80. Please make sure you are not running a web server on your machine!
error: Error Code: EADDRINUSE
error: ===============================

but if i stop the apache server and run everything is going fine but i see that node run port 80 and 443 on all the ip on the machine
netstat -nap | grep :80
tcp6       0      0 :::80                   :::*                    LISTEN      16013/node 
netstat -nap | grep :443
tcp6       0      0 :::443                  :::*                    LISTEN      16137/node

So my question is there is some way to set up to run on port 80 and 443 on a single ip? 

Thanks in advance

**Comment by OstlerDev** [comment]
It should be per IP, can you try killing all node processes and trying again? Are you sure Apache is on the other IP?

**Comment by JakeRound** [comment]
@brunojalves Hey! When you've managed to setup the server under ubuntu. Mind creating a tutorial on the github wiki? I'm sure it can help many people including myself. Many thanks :+1:

**Comment by OstlerDev** [comment]
I just tested the fix on my server and the new fix works (it only binds to the specified IP now)

Please test it out and let me know if this fix has worked for you.

**Comment by OstlerDev** [comment]
@JakeRound I will put up a guide for this once I have moved into my new apartment. Because of the moving I have not been able to work a lot on PopcornTV.

**Comment by JakeRound** [comment]
Thank you very much!

**Comment by OstlerDev** [comment]
@JakeRound I most likely will not include a guide on how to run it with apache at the same time, but I will however make a guide on everything needed to run it normally.

**Comment by brunojalves** [comment]
@OstlerDev So the problem with the ports ara solved but wen i try to oppen a movia e have this error 
```
Debug: === Ending MoviesGrid.xml Generation ===
Debug: Query: {}
Web: /js/utils.js
Debug: Query: {"torrentID":"4240","UDID":"C1MN93VPFF54"}
Debug: Streamer: No Stream Running
Debug: === Ending MoviePrePlay.xml Generation ===
Debug: === Getting Movie ===
Debug: https://yts.to/api/v2/movie_details.json?with_images=true&with_cast=true&movie_id=4240
Web: /Movies/MoviePrePlay.xml
Debug:  
{ id: 4240,
  url: 'https://yts.to/movie/paul-blart-mall-cop-2-2015',
  imdb_code: 'tt3450650',
  title: 'Paul Blart: Mall Cop 2',
  title_long: 'Paul Blart: Mall Cop 2 (2015)',
  slug: 'paul-blart-mall-cop-2-2015',
  year: 2015,
  rating: 4,
  runtime: 94,
  genres: [ 'Action', 'Comedy' ],
  language: 'English',
  mpa_rating: 'PG',
  download_count: 410006,
  like_count: 144,
  rt_critics_score: 6,
  rt_critics_rating: 'Rotten',
  rt_audience_score: 43,
  rt_audience_rating: 'Spilled',
  description_intro: 'After six years of keeping our malls safe, Paul Blart has earned a well-deserved vacation. He heads to Vegas with his teenage daughter before she heads off to college. But safety never takes a holiday and when duty calls, Blart answers.',
  description_full: 'After six years of keeping our malls safe, Paul Blart has earned a well-deserved vacation. He heads to Vegas with his teenage daughter before she heads off to college. But safety never takes a holiday and when duty calls, Blart answers.',
  yt_trailer_code: 'v1oi-RkCLNM',
  date_uploaded: '2015-06-26 12:11:31',
  date_uploaded_unix: 1435277491,
  images: 
   { background_image: 'https://s.ynet.io/assets/images/movies/paul_blart_mall_cop_2_2015/background.jpg',
     small_cover_image: 'https://s.ynet.io/assets/images/movies/paul_blart_mall_cop_2_2015/small-cover.jpg',
     medium_cover_image: 'https://s.ynet.io/assets/images/movies/paul_blart_mall_cop_2_2015/medium-cover.jpg',
     large_cover_image: 'https://s.ynet.io/assets/images/movies/paul_blart_mall_cop_2_2015/large-cover.jpg',
     medium_screenshot_image1: 'https://s.ynet.io/assets/images/movies/paul_blart_mall_cop_2_2015/medium-screenshot1.jpg',
     medium_screenshot_image2: 'https://s.ynet.io/assets/images/movies/paul_blart_mall_cop_2_2015/medium-screenshot2.jpg',
     medium_screenshot_image3: 'https://s.ynet.io/assets/images/movies/paul_blart_mall_cop_2_2015/medium-screenshot3.jpg',
     large_screenshot_image1: 'https://s.ynet.io/assets/images/movies/paul_blart_mall_cop_2_2015/large-screenshot1.jpg',
     large_screenshot_image2: 'https://s.ynet.io/assets/images/movies/paul_blart_mall_cop_2_2015/large-screenshot2.jpg',
     large_screenshot_image3: 'https://s.ynet.io/assets/images/movies/paul_blart_mall_cop_2_2015/large-screenshot3.jpg' },
  torrents: 
   [ { url: 'https://yts.to/torrent/download/D767C7ABD49629053A5C2CD8AECA37033C064732.torrent',
       hash: 'D767C7ABD49629053A5C2CD8AECA37033C064732',
       quality: '720p',
       resolution: '1280*688',
       framerate: 23.976,
       seeds: 13670,
       peers: 4226,
       size: '749.39 MB',
       size_bytes: 785790672,
       download_count: 264987,
       date_uploaded: '2015-06-26 12:11:40',
       date_uploaded_unix: 1435277500 },
     { url: 'https://yts.to/torrent/download/0AEDB8FCCA64CFB4506B12F82D069755F138E3E2.torrent',
       hash: '0AEDB8FCCA64CFB4506B12F82D069755F138E3E2',
       quality: '1080p',
       resolution: '1920*1040',
       framerate: 23.976,
       seeds: 5487,
       peers: 3010,
       size: '1.43 GB',
       size_bytes: 1535884883,
       download_count: 145019,
       date_uploaded: '2015-06-26 19:46:42',
       date_uploaded_unix: 1435304802 } ],
  directors: 
   [ { name: 'Andy Fickman',
       small_image: 'https://s.ynet.io/assets/images/directors/thumb/nm0275698.jpg',
       medium_image: 'https://s.ynet.io/assets/images/directors/nm0275698.jpg' } ],
  actors: 
   [ { name: 'Kevin James',
       character_name: 'Paul Blart',
       small_image: 'https://s.ynet.io/assets/images/actors/thumb/nm0416673.jpg',
       medium_image: 'https://s.ynet.io/assets/images/actors/nm0416673.jpg' },
     { name: 'Raini Rodriguez',
       character_name: 'Maya',
       small_image: 'https://s.ynet.io/assets/images/actors/thumb/nm2263115.jpg',
       medium_image: 'https://s.ynet.io/assets/images/actors/nm2263115.jpg' },
     { name: 'Eduardo Verastegui',
       character_name: 'Eduardo Furtillo',
       small_image: 'https://s.ynet.io/assets/images/actors/thumb/nm0895150.jpg',
       medium_image: 'https://s.ynet.io/assets/images/actors/nm0895150.jpg' },
     { name: 'Daniella Alonso',
       character_name: 'Divina',
       small_image: 'https://s.ynet.io/assets/images/actors/thumb/nm0022161.jpg',
       medium_image: 'https://s.ynet.io/assets/images/actors/nm0022161.jpg' } ] }
/home/balves/popcorn/PopcornTV-master/node_modules/images/binding.js:55
                throw new Error('Can\'t load the addon. Issue to: ' + bugUrl +
                      ^
Error: Can't load the addon. Issue to: https://github.com/zhangyuanwei/node-images/issues Error: Cannot find module './bindings/linux/ia32/0.12.0/binding.node'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/balves/popcorn/PopcornTV-master/node_modules/images/binding.js:52:34)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/balves/popcorn/PopcornTV-master/node_modules/images/binding.js:55:23)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/balves/popcorn/PopcornTV-master/node_modules/images/index.js:4:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

**Comment by OstlerDev** [comment]
@brunojalves Please attempt to run ``npm install`` again, that should solve your issue.

**Comment by brunojalves** [comment]
@OstlerDev Same problem
```
Debug:  
{ id: 4158,
  url: 'https://yts.to/movie/run-all-night-2015',
  imdb_code: 'tt2199571',
  title: 'Run All Night',
  title_long: 'Run All Night (2015)',
  slug: 'run-all-night-2015',
  year: 2015,
  rating: 6.8,
  runtime: 114,
  genres: [ 'Action', 'Crime' ],
  language: 'English',
  mpa_rating: 'R',
  download_count: 1080485,
  like_count: 458,
  rt_critics_score: 61,
  rt_critics_rating: 'Fresh',
  rt_audience_score: 62,
  rt_audience_rating: 'Upright',
  description_intro: 'Mobster and hit man Jimmy Conlon has one night to figure out where his loyalties lie: with his estranged son, Mike, whose life is in danger, or his longtime best friend, mob boss Shawn Maguire, who wants Mike to pay for the death of his own son.',
  description_full: 'Professional Brooklyn hitman Jimmy Conlon is more commonly known as THE GRAVEDIGGER. Jimmy was a mob hit-man, who was best friends with his boss Sean Maguire. But when Jimmy\'s son, Michael, is marked for death by the mob, Jimmy must go up against Sean to protect Michael at all costs. Together, he and Michael must avoid corrupt cops, contract killers and the mob to survive the night.',
  yt_trailer_code: '7uDuFh-nC-c',
  date_uploaded: '2015-06-03 11:51:40',
  date_uploaded_unix: 1433289100,
  images: 
   { background_image: 'https://s.ynet.io/assets/images/movies/run_all_night_2015/background.jpg',
     small_cover_image: 'https://s.ynet.io/assets/images/movies/run_all_night_2015/small-cover.jpg',
     medium_cover_image: 'https://s.ynet.io/assets/images/movies/run_all_night_2015/medium-cover.jpg',
     large_cover_image: 'https://s.ynet.io/assets/images/movies/run_all_night_2015/large-cover.jpg',
     medium_screenshot_image1: 'https://s.ynet.io/assets/images/movies/run_all_night_2015/medium-screenshot1.jpg',
     medium_screenshot_image2: 'https://s.ynet.io/assets/images/movies/run_all_night_2015/medium-screenshot2.jpg',
     medium_screenshot_image3: 'https://s.ynet.io/assets/images/movies/run_all_night_2015/medium-screenshot3.jpg',
     large_screenshot_image1: 'https://s.ynet.io/assets/images/movies/run_all_night_2015/large-screenshot1.jpg',
     large_screenshot_image2: 'https://s.ynet.io/assets/images/movies/run_all_night_2015/large-screenshot2.jpg',
     large_screenshot_image3: 'https://s.ynet.io/assets/images/movies/run_all_night_2015/large-screenshot3.jpg' },
  torrents: 
   [ { url: 'https://yts.to/torrent/download/0BAB52816F1586CB2BADF444A649A8F01ED30D5C.torrent',
       hash: '0BAB52816F1586CB2BADF444A649A8F01ED30D5C',
       quality: '720p',
       resolution: '1280*536',
       framerate: 23.976,
       seeds: 9186,
       peers: 1513,
       size: '814.52 MB',
       size_bytes: 854083027,
       download_count: 646442,
       date_uploaded: '2015-06-03 11:51:47',
       date_uploaded_unix: 1433289107 },
     { url: 'https://yts.to/torrent/download/9D535CC988C98BBC45630F0CD2EAC7021EAEC303.torrent',
       hash: '9D535CC988C98BBC45630F0CD2EAC7021EAEC303',
       quality: '1080p',
       resolution: '1920*800',
       framerate: 23.976,
       seeds: 4233,
       peers: 1036,
       size: '1.84 GB',
       size_bytes: 1976531386,
       download_count: 434043,
       date_uploaded: '2015-06-03 18:29:04',
       date_uploaded_unix: 1433312944 } ],
  directors: 
   [ { name: 'Jaume Collet-Serra',
       small_image: 'https://s.ynet.io/assets/images/directors/thumb/nm1429471.jpg',
       medium_image: 'https://s.ynet.io/assets/images/directors/nm1429471.jpg' } ],
  actors: 
   [ { name: 'Liam Neeson',
       character_name: 'Jimmy Conlon',
       small_image: 'https://s.ynet.io/assets/images/actors/thumb/nm0000553.jpg',
       medium_image: 'https://s.ynet.io/assets/images/actors/nm0000553.jpg' },
     { name: 'Ed Harris',
       character_name: 'Shawn Maguire',
       small_image: 'https://s.ynet.io/assets/images/actors/thumb/nm0000438.jpg',
       medium_image: 'https://s.ynet.io/assets/images/actors/nm0000438.jpg' },
     { name: 'Joel Kinnaman',
       character_name: 'Mike Conlon',
       small_image: 'https://s.ynet.io/assets/images/actors/thumb/nm1172478.jpg',
       medium_image: 'https://s.ynet.io/assets/images/actors/nm1172478.jpg' },
     { name: 'Vincent D\'Onofrio',
       character_name: 'Detective Harding',
       small_image: 'https://s.ynet.io/assets/images/actors/thumb/nm0000352.jpg',
       medium_image: 'https://s.ynet.io/assets/images/actors/nm0000352.jpg' } ] }
/home/balves/popcorn/PopcornTV-master/node_modules/images/binding.js:55
                throw new Error('Can\'t load the addon. Issue to: ' + bugUrl +
                      ^
Error: Can't load the addon. Issue to: https://github.com/zhangyuanwei/node-images/issues Error: Cannot find module './bindings/linux/ia32/0.12.0/binding.node'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/balves/popcorn/PopcornTV-master/node_modules/images/binding.js:52:34)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/balves/popcorn/PopcornTV-master/node_modules/images/binding.js:55:23)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/balves/popcorn/PopcornTV-master/node_modules/images/index.js:4:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

```

Any idea?

**Comment by OstlerDev** [comment]
It is an issue with Node-Images, a library that I use for image combining. Try deleting "node-modules" and re-running ``npm install``.

It could possibly be an issue where Ubuntu does not have that library support or something, try googling around for a solution.

**Comment by brunojalves** [comment]
Ok Thanks ;) i will try it.

**Comment by brunojalves** [comment]
Just one thing, i solve the problem with ```./bindings/linux/ia32/0.12.0/binding.node```, just add it to server but not i'm getting this error, you know it?
```
Debug: === Generating Fanart ===
Debug: === Getting Fanart ===
Debug: https://api-v2launch.trakt.tv/movies/tt2515034?extended=images
/home/balves/popcorn/PopcornTV-master/node_modules/images/index.js:21
    this._handle = new _Image(width, height);
                   ^
TypeError: undefined is not a function
    at new WrappedImage (/home/balves/popcorn/PopcornTV-master/node_modules/images/index.js:21:20)
    at WrappedImage (/home/balves/popcorn/PopcornTV-master/node_modules/images/index.js:14:49)
    at Function.images.loadFromBuffer (/home/balves/popcorn/PopcornTV-master/node_modules/images/index.js:167:12)
    at Function.images.loadFromFile (/home/balves/popcorn/PopcornTV-master/node_modules/images/index.js:159:19)
    at images (/home/balves/popcorn/PopcornTV-master/node_modules/images/index.js:127:24)
    at WriteStream.<anonymous> (/home/balves/popcorn/PopcornTV-master/fanartGenerator.js:27:25)
    at WriteStream.emit (events.js:129:20)
    at finishMaybe (_stream_writable.js:484:14)
    at afterWrite (_stream_writable.js:362:3)
    at onwrite (_stream_writable.js:352:7)
```

**Comment by OstlerDev** [comment]
That seems to be an error with node-images. Not sure at all why it would be happening, you would need to submit a bug report to them here: https://github.com/zhangyuanwei/node-images/issues

I personally run PopcornTV on a CentOS server and it works great. I have not done any testing with Ubuntu.

**Comment by OstlerDev** [comment]
Did you get your issue resolved?

**Comment by brunojalves** [comment]
Hi @OstlerDev, Yes i solve it making this changes:

```
cd /home/balves/popcorn/PopcornTV-master/node_modules
rm -rf images
git clone https://github.com/zhangyuanwei/node-images
cd node-images/
git submodule init
git submodule update
cd gyp
sh third-party.sh
cd ..
npm install
node-gyp rebuild
cd ..
mv node-images images
```

And install this ```apt-get install cmake```

Thanks for your support and for this awesome work.
