### ISSUE TITLE
Cannot find module 'file-type'

### ISSUE THREAD

**Issue by lemonhead94** [OstlerDev/PopcornTV#74]
notice: Starting PopcornTV
DNS: DnsProxy binding on IP:53
error: There is an error starting Popcorn TV, please post this on the Github page
error:  Error: Cannot find module 'file-type'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/Name/Projects/PopcornTV/streamer-server.js:14:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

**Comment by masonjames** [comment]
Make sure you're in the correct PopcornTV directory and try running npm install again.

For reference: http://stackoverflow.com/questions/9023672/nodejs-how-to-resolve-cannot-find-module-error

**Comment by lemonhead94** [comment]
oh shit i actually forgot to build the module, that was stupid.

Yeah, it does indeed work now...

**Comment by OstlerDev** [comment]
Glad that it works for you now. Thank you @masonjames for assisting.

**Comment by masonjames** [comment]
:) I can help on the easy ones.  I've made many of the stupid mistakes myself, though I'm sure I'll find more
